# Introduction

On the notebook "determining_redshifht", I used a random sample of 15000 stellar objects(5000 of stars, QSOs and galaxies) from the SDSS catalogue to determing the redshifts (z, distance measurement) of the stellar objects in the sample. In order to calculate z, I use the magnitudes of the 5 SDSS bands of each stellar object. To do this, I used two regression learning algorithms(KNearest Neighbor and Support Vector Machine). I compared the resulting values of mean squared error(mse) of the predicted values to spectroscopic z with the mse of the photometric z provided by the SDSS to its spectroscopic counterpart. I found that the mse of the last one to be 0.054 and the mse of the predicted values to be 0.186. This value which is too high, i found that it was due to the presence of higher z. Separaing the sample by z= 1, the mse of the best model for sources with z <=1 to be 0.008 and for the other subsample to be 0.099. I then used neural networks to predict the values of z which is in the notebook "determining_redshift_NN". 

In this notebook, I do the same analysis as the previous notebook but I added colour(difference between the magnitudes of two bands) information to the sample. To compare the mse of this study to the one of the initial notebook, the mse of the coloured sample is 0.149.

In [1]:
import os
import numpy as np
import pandas as pd
from pandas.plotting import table
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
sns.set()
%matplotlib inline
import tensorflow as tf
import tensorflow_docs as tfdocs
import tensorflow_docs.modeling
import tensorflow_docs.plots
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
import scikeras
from scikeras.wrappers import KerasRegressor
from keras.layers import LeakyReLU

In [2]:
#Loading files
filepath= "/home/veroastro/Documents/spectraTypes/MLphotometry/data/"
galaxy = pd.read_csv(filepath+"galaxy_nophotoZ4.csv")
star = pd.read_csv(filepath+"star_nophotoZ.csv")
QSO = pd.read_csv(filepath+"QSO_nophotoZ.csv")
#Create the data frame from the three sets of data
data = pd.concat([star, QSO, galaxy])
#Scramble the data set so that it is not ordered by spectral class (QSO, galaxy or star) 
data = data.sample(frac=1)
# Removing Id, error and class data
data_clean = data.drop(columns=['objID','err_u', 'err_g', 'err_r', 'err_i', 'err_z', 'zErr', 'class', 'subClass', 'type', 'zWarning'])
data_clean.head()

dered_u   dered_g   dered_r   dered_i   dered_z         z
3660  19.92751  18.19411  17.42766  17.06925  16.76144  0.055536
1187  19.65844  19.45745  18.97910  18.96488  19.02022  1.275659
3414  19.43212  19.23183  19.20471  19.00803  18.99661  1.783297
678   19.54354  18.60906  18.38204  18.27748  18.27099  0.000079
4606  18.71689  18.68441  18.70579  18.49688  18.45490  1.847776

In [3]:
# Create a function to calculate the colours of the sources
def compute_colour(row):
    u = row['dered_u']
    g = row['dered_g']
    r = row['dered_r']
    i = row['dered_i']
    z = row['dered_z']
    return pd.Series({'u-g': u - g, 'g-r': g - r, 'r-i': r - i, 'i-z': i - z})
# Apply the function compute_colour
colour_ind = data_clean.apply(compute_colour, axis=1)
# Create new dataframe with the colours added
data_colour = pd.concat([data_clean,colour_ind], axis=1)
data_colour.describe()

dered_u       dered_g       dered_r       dered_i       dered_z  \
count  15000.000000  15000.000000  15000.000000  15000.000000  15000.000000   
mean      19.278773     18.242983     17.803544     17.590448     17.445029   
std        1.073886      1.280207      1.444430      1.521226      1.569711   
min        7.552934      7.661058      8.319589     10.746470      8.741409   
25%       18.716025     17.467247     16.804580     16.486115     16.265550   
50%       19.425340     18.242070     17.639700     17.365905     17.256925   
75%       20.037327     19.222772     19.024073     18.929403     18.864542   
max       21.546420     22.145940     21.324990     21.340340     20.616610   

                  z           u-g           g-r           r-i           i-z  
count  1.500000e+04  15000.000000  15000.000000  15000.000000  15000.000000  
mean   5.338676e-01      1.035791      0.439438      0.213096      0.145420  
std    8.067329e-01      0.647352      0.350960      0.196789      0.171565  
min    5.417808e-09     -1.391450     -1.454840     -3.861471     -1.146380  
25%    3.022298e-04      0.465475      0.174497      0.087350      0.027745  
50%    8.968894e-02      1.048255      0.382455      0.202605      0.133620  
75%    9.271685e-01      1.506298      0.715958      0.372275      0.273913  
max    6.164721e+00      3.653620      3.852890      1.688770      3.762850

In [4]:
# creating the features and label dataframes and normalising X
from sklearn.preprocessing import RobustScaler
X = data_colour.drop(['z'], axis=1)
y = data_colour['z']
scaler = RobustScaler()
X_t = scaler.fit_transform(X)

In [5]:
# divide the X and y dataframsn into train and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_t, y, 
                                                    test_size=0.3, random_state=42)

In [6]:
parameters=[
    {
        "name": "learning_rate",
        "type": "range",
        "bounds": [0.001, 0.5],
        "log_scale": True,
    },
    {
        "name": "dropout_rate",
        "type": "range",
        "bounds": [0.01, 0.9],
        "log_scale": True,
    },
    {
        "name": "num_hidden_layers",
        "type": "range",
        "bounds": [1, 7],
        "value_type": "int"
    },
    {
        "name": "neurons_per_layer",
        "type": "range",
        "bounds": [1, 300],
        "value_type": "int"
    },
    {
        "name": "batch_size",
        "type": "choice",
        "values": [8, 10, 16, 20, 30],
    },
    
    {
        "name": "activation",
        "type": "choice",
        "values": [ 'LeakyReLU(alpha=0.3)', 'relu'],
    },
    {
        "name": "optimizer",
        "type": "choice",
        "values": ['adam', 'rms', 'sgd'],
    },
]

In [7]:
# This returns a multi-layer-perceptron model in Keras.
def get_keras_model(num_hidden_layers, 
                    num_neurons_per_layer, 
                    dropout_rate, 
                    activation):
    # create the MLP model.
    
    # define the layers.
    inputs = tf.keras.Input(shape=(X_train.shape[1],))  # input layer.
    x = Dropout(dropout_rate)(inputs) # dropout on the weights.
    
    # Add the hidden layers.
    for i in range(num_hidden_layers):
        x = Dense(num_neurons_per_layer, 
                         activation=activation)(x)
        x = Dropout(dropout_rate)(x)
    
    # output layer.
    outputs = Dense(1, activation='linear')(x)
    
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    return model

In [8]:
# This function takes in the hyperparameters and returns a score (Cross validation). 
# Returns the mean of the validation loss based on which we decide which algorithm has the best hyperparameters
def keras_mlp_cv_score(parameterization, weight=None):
    
    model = get_keras_model(parameterization.get('num_hidden_layers'),
                            parameterization.get('neurons_per_layer'),
                            parameterization.get('dropout_rate'),
                            parameterization.get('activation'))
    
    opt = parameterization.get('optimizer')
    opt = opt.lower()
    
    learning_rate = parameterization.get('learning_rate')
    
    if opt == 'adam':
        optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
    elif opt == 'rms':
        optimizer = tf.keras.optimizers.RMSprop(learning_rate=learning_rate)
    else:
        optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate)
        
    act = parameterization.get('activation')
    act = act.lower()
    
    if act == 'leakyrelu': 
        activation = ""
        get_keras_model.add(leakyReLU())
    
    
    NUM_EPOCHS = 100
    
    # Specify the training configuration.
    model.compile(optimizer=optimizer,
                  loss=tf.keras.losses.MeanSquaredError(),
                  metrics=['mae', 'mse'] )

    data = X_train
    labels = y_train.values
    
    early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10)

    
    # fit the model using a 20% validation set. with a patience of 10 to avoid overfitting
    res = model.fit(data, labels, epochs=NUM_EPOCHS, batch_size=parameterization.get('batch_size'),
                    validation_split=0.2, callbacks=[early_stop, tfdocs.modeling.EpochDots()])
    
    # look at the last 10 epochs. Get the mean and standard deviation of the validation score.
    last10_scores = np.array(res.history['val_loss'][-10:])
    mean = last10_scores.mean()
    sem = last10_scores.std()
    
    # If the model didn't converge then set a high loss.
    if np.isnan(mean):
        return 9999.0, 0.0
    
    return mean, sem

In [9]:
import optuna

# Define the objective function for Optuna.
def objective(trial):
    # Sample hyperparameters from the ranges defined in `parameters`.
    learning_rate = trial.suggest_loguniform('learning_rate', 0.001, 0.5)
    dropout_rate = trial.suggest_loguniform('dropout_rate', 0.01, 0.9)
    num_hidden_layers = trial.suggest_int('num_hidden_layers', 1, 7)
    neurons_per_layer = trial.suggest_int('neurons_per_layer', 1, 300)
    batch_size = trial.suggest_categorical('batch_size', [8, 10, 16, 20, 30])
    activation = trial.suggest_categorical('activation', [ 'relu'])
    optimizer = trial.suggest_categorical('optimizer', ['adam', 'rms', 'sgd'])

    # Set the hyperparameters in a dictionary to pass to `keras_mlp_cv_score`.
    parameterization = {
        'learning_rate': learning_rate,
        'dropout_rate': dropout_rate,
        'num_hidden_layers': num_hidden_layers,
        'neurons_per_layer': neurons_per_layer,
        'batch_size': batch_size,
        'activation': activation,
        'optimizer': optimizer
    }

    # Call `keras_mlp_cv_score` to get the cross-validation score.
    score, _ = keras_mlp_cv_score(parameterization)

    return score

# Use Optuna to optimize the neural network.
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=100)

# Get the best hyperparameters and the best score.
best_params = study.best_params
best_score = study.best_value


[I 2023-04-27 08:43:12,307] A new study created in memory with name: no-name-59684a1a-9e9e-4886-9486-9bbc4189a09e
/tmp/ipykernel_134456/649837142.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 0.001, 0.5)
/tmp/ipykernel_134456/649837142.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  dropout_rate = trial.suggest_loguniform('dropout_rate', 0.01, 0.9)
2023-04-27 08:43:17.940713: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-04-27 08:43:17.940745: I tensorflow/stream_executor/cuda/cuda_diag

Epoch 1/100
839/840 [============================>.] - ETA: 0s - loss: 3.1595 - mae: 0.6588 - mse: 3.1595
Epoch: 0, loss:3.1574,  mae:0.6592,  mse:3.1574,  val_loss:0.6474,  val_mae:0.6381,  val_mse:0.6474,  
840/840 [==============================] - 3s 3ms/step - loss: 3.1574 - mae: 0.6592 - mse: 3.1574 - val_loss: 0.6474 - val_mae: 0.6381 - val_mse: 0.6474
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 1.0388 - mae: 0.6709 - mse: 1.0388 - val_loss: 0.6456 - val_mae: 0.6635 - val_mse: 0.6456
Epoch 3/100
840/840 [==============================] - 2s 3ms/step - loss: 0.6626 - mae: 0.6638 - mse: 0.6626 - val_loss: 0.6527 - val_mae: 0.6219 - val_mse: 0.6527
Epoch 4/100
840/840 [==============================] - 2s 3ms/step - loss: 0.6571 - mae: 0.6619 - mse: 0.6571 - val_loss: 0.6492 - val_mae: 0.6312 - val_mse: 0.6492
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.6546 - mae: 0.6613 - mse: 0.6546 - val_loss: 0.6741 - val_mae: 0.7

[I 2023-04-27 08:44:13,521] Trial 0 finished with value: 0.6521165072917938 and parameters: {'learning_rate': 0.07935912349515462, 'dropout_rate': 0.014928486176737114, 'num_hidden_layers': 6, 'neurons_per_layer': 51, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'adam'}. Best is trial 0 with value: 0.6521165072917938.


Epoch 1/100
824/840 [============================>.] - ETA: 0s - loss: 0.3940 - mae: 0.4034 - mse: 0.3940
Epoch: 0, loss:0.3925,  mae:0.4032,  mse:0.3925,  val_loss:0.2973,  val_mae:0.3577,  val_mse:0.2973,  
840/840 [==============================] - 3s 3ms/step - loss: 0.3925 - mae: 0.4032 - mse: 0.3925 - val_loss: 0.2973 - val_mae: 0.3577 - val_mse: 0.2973
Epoch 2/100
840/840 [==============================] - 1s 2ms/step - loss: 0.3160 - mae: 0.3655 - mse: 0.3160 - val_loss: 0.2748 - val_mae: 0.3373 - val_mse: 0.2748
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.3001 - mae: 0.3509 - mse: 0.3001 - val_loss: 0.2615 - val_mae: 0.3217 - val_mse: 0.2615
Epoch 4/100
840/840 [==============================] - 3s 3ms/step - loss: 0.2879 - mae: 0.3372 - mse: 0.2879 - val_loss: 0.2529 - val_mae: 0.3086 - val_mse: 0.2529
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2875 - mae: 0.3312 - mse: 0.2875 - val_loss: 0.2474 - val_mae: 0.3

840/840 [==============================] - 1s 2ms/step - loss: 0.2091 - mae: 0.2533 - mse: 0.2091 - val_loss: 0.1615 - val_mae: 0.2093 - val_mse: 0.1615
Epoch 99/100
840/840 [==============================] - 1s 2ms/step - loss: 0.2084 - mae: 0.2511 - mse: 0.2084 - val_loss: 0.1595 - val_mae: 0.2084 - val_mse: 0.1595
Epoch 100/100
840/840 [==============================] - 1s 2ms/step - loss: 0.2075 - mae: 0.2514 - mse: 0.2075 - val_loss: 0.1592 - val_mae: 0.2084 - val_mse: 0.1592


[I 2023-04-27 08:46:45,112] Trial 1 finished with value: 0.16051052808761596 and parameters: {'learning_rate': 0.0010141702570265739, 'dropout_rate': 0.054162509005370084, 'num_hidden_layers': 2, 'neurons_per_layer': 145, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 1 with value: 0.16051052808761596.


Epoch 1/100
409/420 [============================>.] - ETA: 0s - loss: 0.3670 - mae: 0.3606 - mse: 0.3670
Epoch: 0, loss:0.3635,  mae:0.3580,  mse:0.3635,  val_loss:0.2200,  val_mae:0.2549,  val_mse:0.2200,  
420/420 [==============================] - 1s 2ms/step - loss: 0.3635 - mae: 0.3580 - mse: 0.3635 - val_loss: 0.2200 - val_mae: 0.2549 - val_mse: 0.2200
Epoch 2/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2869 - mae: 0.3144 - mse: 0.2869 - val_loss: 0.2871 - val_mae: 0.3321 - val_mse: 0.2871
Epoch 3/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2810 - mae: 0.3121 - mse: 0.2810 - val_loss: 0.2078 - val_mae: 0.2153 - val_mse: 0.2078
Epoch 4/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2778 - mae: 0.3022 - mse: 0.2778 - val_loss: 0.2196 - val_mae: 0.2548 - val_mse: 0.2196
Epoch 5/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2766 - mae: 0.2977 - mse: 0.2766 - val_loss: 0.1928 - val_mae: 0.2

[I 2023-04-27 08:47:02,451] Trial 2 finished with value: 0.21045135855674743 and parameters: {'learning_rate': 0.01957061726989641, 'dropout_rate': 0.06520581786917656, 'num_hidden_layers': 3, 'neurons_per_layer': 54, 'batch_size': 20, 'activation': 'relu', 'optimizer': 'rms'}. Best is trial 1 with value: 0.16051052808761596.


Epoch 1/100
1043/1050 [============================>.] - ETA: 0s - loss: 335.9552 - mae: 1.8201 - mse: 335.9552
Epoch: 0, loss:333.7191,  mae:1.8120,  mse:333.7191,  val_loss:0.6509,  val_mae:0.6263,  val_mse:0.6509,  
1050/1050 [==============================] - 3s 2ms/step - loss: 333.7191 - mae: 1.8120 - mse: 333.7191 - val_loss: 0.6509 - val_mae: 0.6263 - val_mse: 0.6509
Epoch 2/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.6748 - mae: 0.6589 - mse: 0.6748 - val_loss: 0.6460 - val_mae: 0.6458 - val_mse: 0.6460
Epoch 3/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.6566 - mae: 0.6574 - mse: 0.6566 - val_loss: 0.6455 - val_mae: 0.6515 - val_mse: 0.6455
Epoch 4/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.6866 - mae: 0.6614 - mse: 0.6866 - val_loss: 0.6456 - val_mae: 0.6494 - val_mse: 0.6456
Epoch 5/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.6538 - mae: 0.6616 - mse: 0.6538 - val_los

[I 2023-04-27 08:47:31,497] Trial 3 finished with value: 0.6537161588668823 and parameters: {'learning_rate': 0.18645300006060758, 'dropout_rate': 0.016346328494810786, 'num_hidden_layers': 4, 'neurons_per_layer': 57, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'adam'}. Best is trial 1 with value: 0.16051052808761596.


Epoch 1/100
391/420 [==========================>...] - ETA: 0s - loss: 0.3023 - mae: 0.3403 - mse: 0.3023
Epoch: 0, loss:0.2966,  mae:0.3366,  mse:0.2966,  val_loss:0.2172,  val_mae:0.2617,  val_mse:0.2172,  
420/420 [==============================] - 2s 3ms/step - loss: 0.2966 - mae: 0.3366 - mse: 0.2966 - val_loss: 0.2172 - val_mae: 0.2617 - val_mse: 0.2172
Epoch 2/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2575 - mae: 0.2983 - mse: 0.2575 - val_loss: 0.1914 - val_mae: 0.2380 - val_mse: 0.1914
Epoch 3/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2405 - mae: 0.2810 - mse: 0.2405 - val_loss: 0.1898 - val_mae: 0.2357 - val_mse: 0.1898
Epoch 4/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2320 - mae: 0.2750 - mse: 0.2320 - val_loss: 0.1703 - val_mae: 0.2185 - val_mse: 0.1703
Epoch 5/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2214 - mae: 0.2635 - mse: 0.2214 - val_loss: 0.1613 - val_mae: 0.2

[I 2023-04-27 08:48:30,324] Trial 4 finished with value: 0.12476304471492768 and parameters: {'learning_rate': 0.03178345175334787, 'dropout_rate': 0.058082447133974265, 'num_hidden_layers': 3, 'neurons_per_layer': 133, 'batch_size': 20, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 4 with value: 0.12476304471492768.


Epoch 1/100
823/840 [============================>.] - ETA: 0s - loss: 20.1261 - mae: 1.3997 - mse: 20.1261
Epoch: 0, loss:19.7321,  mae:1.3850,  mse:19.7321,  val_loss:0.6649,  val_mae:0.6126,  val_mse:0.6649,  
840/840 [==============================] - 2s 2ms/step - loss: 19.7321 - mae: 1.3850 - mse: 19.7321 - val_loss: 0.6649 - val_mae: 0.6126 - val_mse: 0.6649
Epoch 2/100
840/840 [==============================] - 1s 2ms/step - loss: 1.5186 - mae: 0.6997 - mse: 1.5186 - val_loss: 0.8131 - val_mae: 0.6962 - val_mse: 0.8131
Epoch 3/100
840/840 [==============================] - 1s 2ms/step - loss: 1.2185 - mae: 0.6971 - mse: 1.2185 - val_loss: 0.6595 - val_mae: 0.7083 - val_mse: 0.6595
Epoch 4/100
840/840 [==============================] - 1s 2ms/step - loss: 0.9350 - mae: 0.6812 - mse: 0.9350 - val_loss: 0.6590 - val_mae: 0.6965 - val_mse: 0.6590
Epoch 5/100
840/840 [==============================] - 1s 2ms/step - loss: 1.2427 - mae: 0.6802 - mse: 1.2427 - val_loss: 0.6729 - val_ma

[I 2023-04-27 08:49:00,070] Trial 5 finished with value: 0.6667379081249237 and parameters: {'learning_rate': 0.17663022666452313, 'dropout_rate': 0.7797319884172609, 'num_hidden_layers': 1, 'neurons_per_layer': 52, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'rms'}. Best is trial 4 with value: 0.12476304471492768.


Epoch 1/100
413/420 [============================>.] - ETA: 0s - loss: 0.4185 - mae: 0.4415 - mse: 0.4185
Epoch: 0, loss:0.4178,  mae:0.4408,  mse:0.4178,  val_loss:0.2731,  val_mae:0.3845,  val_mse:0.2731,  
420/420 [==============================] - 1s 2ms/step - loss: 0.4178 - mae: 0.4408 - mse: 0.4178 - val_loss: 0.2731 - val_mae: 0.3845 - val_mse: 0.2731
Epoch 2/100
420/420 [==============================] - 1s 2ms/step - loss: 0.3624 - mae: 0.3935 - mse: 0.3624 - val_loss: 0.2654 - val_mae: 0.3577 - val_mse: 0.2654
Epoch 3/100
420/420 [==============================] - 1s 2ms/step - loss: 0.3561 - mae: 0.3861 - mse: 0.3561 - val_loss: 0.2731 - val_mae: 0.3055 - val_mse: 0.2731
Epoch 4/100
420/420 [==============================] - 1s 2ms/step - loss: 0.3305 - mae: 0.3644 - mse: 0.3305 - val_loss: 0.2501 - val_mae: 0.3439 - val_mse: 0.2501
Epoch 5/100
420/420 [==============================] - 1s 2ms/step - loss: 0.3422 - mae: 0.3685 - mse: 0.3422 - val_loss: 0.2633 - val_mae: 0.3

[I 2023-04-27 08:49:28,987] Trial 6 finished with value: 0.23169954121112823 and parameters: {'learning_rate': 0.16586659915145824, 'dropout_rate': 0.374949388797916, 'num_hidden_layers': 2, 'neurons_per_layer': 67, 'batch_size': 20, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 4 with value: 0.12476304471492768.


Epoch 1/100
828/840 [============================>.] - ETA: 0s - loss: 0.4048 - mae: 0.4352 - mse: 0.4048
Epoch: 0, loss:0.4061,  mae:0.4355,  mse:0.4061,  val_loss:0.2797,  val_mae:0.4377,  val_mse:0.2797,  
840/840 [==============================] - 3s 3ms/step - loss: 0.4061 - mae: 0.4355 - mse: 0.4061 - val_loss: 0.2797 - val_mae: 0.4377 - val_mse: 0.2797
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.3134 - mae: 0.3759 - mse: 0.3134 - val_loss: 0.2662 - val_mae: 0.3379 - val_mse: 0.2662
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2987 - mae: 0.3631 - mse: 0.2987 - val_loss: 0.2150 - val_mae: 0.3461 - val_mse: 0.2150
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2856 - mae: 0.3629 - mse: 0.2856 - val_loss: 0.2515 - val_mae: 0.4057 - val_mse: 0.2515
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2723 - mae: 0.3381 - mse: 0.2723 - val_loss: 0.1720 - val_mae: 0.2

[I 2023-04-27 08:49:59,767] Trial 7 finished with value: 9999.0 and parameters: {'learning_rate': 0.2891133006314204, 'dropout_rate': 0.01918734373646765, 'num_hidden_layers': 4, 'neurons_per_layer': 162, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 4 with value: 0.12476304471492768.


Epoch 1/100
524/525 [============================>.] - ETA: 0s - loss: 0.6915 - mae: 0.5909 - mse: 0.6915
Epoch: 0, loss:0.6911,  mae:0.5908,  mse:0.6911,  val_loss:0.3860,  val_mae:0.4650,  val_mse:0.3860,  
525/525 [==============================] - 1s 2ms/step - loss: 0.6911 - mae: 0.5908 - mse: 0.6911 - val_loss: 0.3860 - val_mae: 0.4650 - val_mse: 0.3860
Epoch 2/100
525/525 [==============================] - 1s 2ms/step - loss: 0.5420 - mae: 0.5446 - mse: 0.5420 - val_loss: 0.4319 - val_mae: 0.4670 - val_mse: 0.4319
Epoch 3/100
525/525 [==============================] - 1s 2ms/step - loss: 0.5267 - mae: 0.5374 - mse: 0.5267 - val_loss: 0.4193 - val_mae: 0.4865 - val_mse: 0.4193
Epoch 4/100
525/525 [==============================] - 1s 2ms/step - loss: 0.5418 - mae: 0.5502 - mse: 0.5418 - val_loss: 0.4288 - val_mae: 0.4790 - val_mse: 0.4288
Epoch 5/100
525/525 [==============================] - 1s 2ms/step - loss: 0.5479 - mae: 0.5502 - mse: 0.5479 - val_loss: 0.4470 - val_mae: 0.4

[I 2023-04-27 08:50:11,784] Trial 8 finished with value: 0.4487859785556793 and parameters: {'learning_rate': 0.0035474751039798707, 'dropout_rate': 0.8157153273833954, 'num_hidden_layers': 1, 'neurons_per_layer': 300, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'adam'}. Best is trial 4 with value: 0.12476304471492768.


Epoch 1/100
522/525 [============================>.] - ETA: 0s - loss: 0.4481 - mae: 0.4303 - mse: 0.4481
Epoch: 0, loss:0.4477,  mae:0.4303,  mse:0.4477,  val_loss:0.3544,  val_mae:0.3731,  val_mse:0.3544,  
525/525 [==============================] - 2s 3ms/step - loss: 0.4477 - mae: 0.4303 - mse: 0.4477 - val_loss: 0.3544 - val_mae: 0.3731 - val_mse: 0.3544
Epoch 2/100
525/525 [==============================] - 1s 3ms/step - loss: 0.3857 - mae: 0.3859 - mse: 0.3857 - val_loss: 0.3006 - val_mae: 0.3702 - val_mse: 0.3006
Epoch 3/100
525/525 [==============================] - 2s 3ms/step - loss: 0.3655 - mae: 0.3812 - mse: 0.3655 - val_loss: 0.2728 - val_mae: 0.3369 - val_mse: 0.2728
Epoch 4/100
525/525 [==============================] - 1s 2ms/step - loss: 0.3529 - mae: 0.3784 - mse: 0.3529 - val_loss: 0.2477 - val_mae: 0.3217 - val_mse: 0.2477
Epoch 5/100
525/525 [==============================] - 1s 3ms/step - loss: 0.3569 - mae: 0.3831 - mse: 0.3569 - val_loss: 0.2517 - val_mae: 0.3

[I 2023-04-27 08:50:32,969] Trial 9 finished with value: 0.2756064236164093 and parameters: {'learning_rate': 0.0018632001700511463, 'dropout_rate': 0.42964737425798655, 'num_hidden_layers': 4, 'neurons_per_layer': 113, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'rms'}. Best is trial 4 with value: 0.12476304471492768.


Epoch 1/100
277/280 [============================>.] - ETA: 0s - loss: 0.3751 - mae: 0.3971 - mse: 0.3751
Epoch: 0, loss:0.3755,  mae:0.3969,  mse:0.3755,  val_loss:0.2662,  val_mae:0.3146,  val_mse:0.2662,  
280/280 [==============================] - 2s 5ms/step - loss: 0.3755 - mae: 0.3969 - mse: 0.3755 - val_loss: 0.2662 - val_mae: 0.3146 - val_mse: 0.2662
Epoch 2/100
280/280 [==============================] - 2s 6ms/step - loss: 0.3084 - mae: 0.3401 - mse: 0.3084 - val_loss: 0.2250 - val_mae: 0.2861 - val_mse: 0.2250
Epoch 3/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2893 - mae: 0.3276 - mse: 0.2893 - val_loss: 0.2146 - val_mae: 0.2681 - val_mse: 0.2146
Epoch 4/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2746 - mae: 0.3130 - mse: 0.2746 - val_loss: 0.2041 - val_mae: 0.2635 - val_mse: 0.2041
Epoch 5/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2682 - mae: 0.3073 - mse: 0.2682 - val_loss: 0.1886 - val_mae: 0.2

[I 2023-04-27 08:51:46,299] Trial 10 finished with value: 0.14906112253665924 and parameters: {'learning_rate': 0.026166149954905675, 'dropout_rate': 0.15203157397084632, 'num_hidden_layers': 7, 'neurons_per_layer': 236, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 4 with value: 0.12476304471492768.


Epoch 1/100
274/280 [============================>.] - ETA: 0s - loss: 0.3647 - mae: 0.3895 - mse: 0.3647
Epoch: 0, loss:0.3643,  mae:0.3885,  mse:0.3643,  val_loss:0.2715,  val_mae:0.3110,  val_mse:0.2715,  
280/280 [==============================] - 2s 5ms/step - loss: 0.3643 - mae: 0.3885 - mse: 0.3643 - val_loss: 0.2715 - val_mae: 0.3110 - val_mse: 0.2715
Epoch 2/100
280/280 [==============================] - 1s 5ms/step - loss: 0.3022 - mae: 0.3338 - mse: 0.3022 - val_loss: 0.2359 - val_mae: 0.2868 - val_mse: 0.2359
Epoch 3/100
280/280 [==============================] - 2s 6ms/step - loss: 0.2835 - mae: 0.3169 - mse: 0.2835 - val_loss: 0.2275 - val_mae: 0.2692 - val_mse: 0.2275
Epoch 4/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2671 - mae: 0.3054 - mse: 0.2671 - val_loss: 0.2056 - val_mae: 0.2642 - val_mse: 0.2056
Epoch 5/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2671 - mae: 0.3044 - mse: 0.2671 - val_loss: 0.1902 - val_mae: 0.2

[I 2023-04-27 08:53:12,796] Trial 11 finished with value: 0.1485651820898056 and parameters: {'learning_rate': 0.024353122383989092, 'dropout_rate': 0.14024279275131019, 'num_hidden_layers': 7, 'neurons_per_layer': 234, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 4 with value: 0.12476304471492768.


Epoch 1/100
279/280 [============================>.] - ETA: 0s - loss: 0.3889 - mae: 0.4075 - mse: 0.3889
Epoch: 0, loss:0.3888,  mae:0.4075,  mse:0.3888,  val_loss:0.2582,  val_mae:0.3058,  val_mse:0.2582,  
280/280 [==============================] - 2s 5ms/step - loss: 0.3888 - mae: 0.4075 - mse: 0.3888 - val_loss: 0.2582 - val_mae: 0.3058 - val_mse: 0.2582
Epoch 2/100
280/280 [==============================] - 1s 4ms/step - loss: 0.3034 - mae: 0.3360 - mse: 0.3034 - val_loss: 0.2369 - val_mae: 0.2867 - val_mse: 0.2369
Epoch 3/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2933 - mae: 0.3260 - mse: 0.2933 - val_loss: 0.2205 - val_mae: 0.2738 - val_mse: 0.2205
Epoch 4/100
280/280 [==============================] - 1s 4ms/step - loss: 0.2809 - mae: 0.3193 - mse: 0.2809 - val_loss: 0.2080 - val_mae: 0.2616 - val_mse: 0.2080
Epoch 5/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2729 - mae: 0.3111 - mse: 0.2729 - val_loss: 0.1941 - val_mae: 0.2

[I 2023-04-27 08:54:05,741] Trial 12 finished with value: 0.1454535499215126 and parameters: {'learning_rate': 0.016579706123707204, 'dropout_rate': 0.1283840079089902, 'num_hidden_layers': 6, 'neurons_per_layer': 207, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 4 with value: 0.12476304471492768.


Epoch 1/100
269/280 [===========================>..] - ETA: 0s - loss: 0.3831 - mae: 0.4062 - mse: 0.3831
Epoch: 0, loss:0.3769,  mae:0.4015,  mse:0.3769,  val_loss:0.2694,  val_mae:0.3226,  val_mse:0.2694,  
280/280 [==============================] - 1s 3ms/step - loss: 0.3769 - mae: 0.4015 - mse: 0.3769 - val_loss: 0.2694 - val_mae: 0.3226 - val_mse: 0.2694
Epoch 2/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2875 - mae: 0.3210 - mse: 0.2875 - val_loss: 0.2423 - val_mae: 0.2915 - val_mse: 0.2423
Epoch 3/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2660 - mae: 0.3000 - mse: 0.2660 - val_loss: 0.2280 - val_mae: 0.2740 - val_mse: 0.2280
Epoch 4/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2575 - mae: 0.2929 - mse: 0.2575 - val_loss: 0.2164 - val_mae: 0.2601 - val_mse: 0.2164
Epoch 5/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2521 - mae: 0.2856 - mse: 0.2521 - val_loss: 0.2063 - val_mae: 0.2

[I 2023-04-27 08:55:27,322] Trial 13 finished with value: 0.11716497093439102 and parameters: {'learning_rate': 0.007534399612709211, 'dropout_rate': 0.03542247453549471, 'num_hidden_layers': 5, 'neurons_per_layer': 201, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
412/420 [============================>.] - ETA: 0s - loss: 0.3587 - mae: 0.3889 - mse: 0.3587
Epoch: 0, loss:0.3575,  mae:0.3880,  mse:0.3575,  val_loss:0.2518,  val_mae:0.3087,  val_mse:0.2518,  
420/420 [==============================] - 2s 3ms/step - loss: 0.3575 - mae: 0.3880 - mse: 0.3575 - val_loss: 0.2518 - val_mae: 0.3087 - val_mse: 0.2518
Epoch 2/100
420/420 [==============================] - 1s 3ms/step - loss: 0.2729 - mae: 0.3078 - mse: 0.2729 - val_loss: 0.2338 - val_mae: 0.2845 - val_mse: 0.2338
Epoch 3/100
420/420 [==============================] - 1s 3ms/step - loss: 0.2631 - mae: 0.2949 - mse: 0.2631 - val_loss: 0.2103 - val_mae: 0.2607 - val_mse: 0.2103
Epoch 4/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2459 - mae: 0.2793 - mse: 0.2459 - val_loss: 0.1997 - val_mae: 0.2451 - val_mse: 0.1997
Epoch 5/100
420/420 [==============================] - 1s 3ms/step - loss: 0.2398 - mae: 0.2728 - mse: 0.2398 - val_loss: 0.1874 - val_mae: 0.2

[I 2023-04-27 08:56:30,983] Trial 14 finished with value: 0.12542012333869934 and parameters: {'learning_rate': 0.007198152589878966, 'dropout_rate': 0.032632437766338535, 'num_hidden_layers': 5, 'neurons_per_layer': 176, 'batch_size': 20, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
1029/1050 [============================>.] - ETA: 0s - loss: 0.3068 - mae: 0.3402 - mse: 0.3068
Epoch: 0, loss:0.3084,  mae:0.3404,  mse:0.3084,  val_loss:0.2344,  val_mae:0.2852,  val_mse:0.2344,  
1050/1050 [==============================] - 3s 2ms/step - loss: 0.3084 - mae: 0.3404 - mse: 0.3084 - val_loss: 0.2344 - val_mae: 0.2852 - val_mse: 0.2344
Epoch 2/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2586 - mae: 0.2951 - mse: 0.2586 - val_loss: 0.2222 - val_mae: 0.2787 - val_mse: 0.2222
Epoch 3/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2377 - mae: 0.2766 - mse: 0.2377 - val_loss: 0.1787 - val_mae: 0.2319 - val_mse: 0.1787
Epoch 4/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2259 - mae: 0.2621 - mse: 0.2259 - val_loss: 0.1794 - val_mae: 0.2314 - val_mse: 0.1794
Epoch 5/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2165 - mae: 0.2543 - mse: 0.2165 - val_loss: 0.1688 - 

[I 2023-04-27 08:58:32,145] Trial 15 finished with value: 0.11789024993777275 and parameters: {'learning_rate': 0.007934896409789921, 'dropout_rate': 0.03321298048785198, 'num_hidden_layers': 5, 'neurons_per_layer': 123, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
1050/1050 [==============================] - ETA: 0s - loss: 0.3055 - mae: 0.3352 - mse: 0.3055
Epoch: 0, loss:0.3055,  mae:0.3352,  mse:0.3055,  val_loss:0.2417,  val_mae:0.2804,  val_mse:0.2417,  
1050/1050 [==============================] - 2s 2ms/step - loss: 0.3055 - mae: 0.3352 - mse: 0.3055 - val_loss: 0.2417 - val_mae: 0.2804 - val_mse: 0.2417
Epoch 2/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2526 - mae: 0.2825 - mse: 0.2526 - val_loss: 0.2113 - val_mae: 0.2694 - val_mse: 0.2113
Epoch 3/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2362 - mae: 0.2658 - mse: 0.2362 - val_loss: 0.1966 - val_mae: 0.2530 - val_mse: 0.1966
Epoch 4/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2221 - mae: 0.2543 - mse: 0.2221 - val_loss: 0.1756 - val_mae: 0.2225 - val_mse: 0.1756
Epoch 5/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2135 - mae: 0.2450 - mse: 0.2135 - val_loss: 0.1665 - 

[I 2023-04-27 09:00:07,864] Trial 16 finished with value: 0.12160329446196556 and parameters: {'learning_rate': 0.0058783594443424, 'dropout_rate': 0.010733151471811262, 'num_hidden_layers': 5, 'neurons_per_layer': 98, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
1045/1050 [============================>.] - ETA: 0s - loss: 0.2975 - mae: 0.3275 - mse: 0.2975
Epoch: 0, loss:0.2970,  mae:0.3271,  mse:0.2970,  val_loss:0.2121,  val_mae:0.2612,  val_mse:0.2121,  
1050/1050 [==============================] - 5s 4ms/step - loss: 0.2970 - mae: 0.3271 - mse: 0.2970 - val_loss: 0.2121 - val_mae: 0.2612 - val_mse: 0.2121
Epoch 2/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2472 - mae: 0.2812 - mse: 0.2472 - val_loss: 0.1943 - val_mae: 0.2415 - val_mse: 0.1943
Epoch 3/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2281 - mae: 0.2623 - mse: 0.2281 - val_loss: 0.1707 - val_mae: 0.2171 - val_mse: 0.1707
Epoch 4/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2154 - mae: 0.2508 - mse: 0.2154 - val_loss: 0.1602 - val_mae: 0.1999 - val_mse: 0.1602
Epoch 5/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2058 - mae: 0.2408 - mse: 0.2058 - val_loss: 0.1553 - 

[I 2023-04-27 09:03:17,060] Trial 17 finished with value: 0.12240209057927132 and parameters: {'learning_rate': 0.008785633016797105, 'dropout_rate': 0.0352361974138985, 'num_hidden_layers': 5, 'neurons_per_layer': 289, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
1022/1050 [============================>.] - ETA: 0s - loss: 0.2938 - mae: 0.3099 - mse: 0.2938
Epoch: 0, loss:0.2905,  mae:0.3081,  mse:0.2905,  val_loss:0.1954,  val_mae:0.2349,  val_mse:0.1954,  
1050/1050 [==============================] - 3s 2ms/step - loss: 0.2905 - mae: 0.3081 - mse: 0.2905 - val_loss: 0.1954 - val_mae: 0.2349 - val_mse: 0.1954
Epoch 2/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2441 - mae: 0.2736 - mse: 0.2441 - val_loss: 0.1856 - val_mae: 0.2499 - val_mse: 0.1856
Epoch 3/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2304 - mae: 0.2616 - mse: 0.2304 - val_loss: 0.1723 - val_mae: 0.2020 - val_mse: 0.1723
Epoch 4/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2254 - mae: 0.2557 - mse: 0.2254 - val_loss: 0.1983 - val_mae: 0.2464 - val_mse: 0.1983
Epoch 5/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2170 - mae: 0.2506 - mse: 0.2170 - val_loss: 0.1551 - 

[I 2023-04-27 09:03:56,575] Trial 18 finished with value: 0.1451980233192444 and parameters: {'learning_rate': 0.0029577220320455106, 'dropout_rate': 0.026787164239546232, 'num_hidden_layers': 6, 'neurons_per_layer': 13, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'adam'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
278/280 [============================>.] - ETA: 0s - loss: 24.6260 - mae: 0.6369 - mse: 24.6260
Epoch: 0, loss:24.4513,  mae:0.6339,  mse:24.4513,  val_loss:0.3259,  val_mae:0.3515,  val_mse:0.3259,  
280/280 [==============================] - 2s 4ms/step - loss: 24.4513 - mae: 0.6339 - mse: 24.4513 - val_loss: 0.3259 - val_mae: 0.3515 - val_mse: 0.3259
Epoch 2/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2933 - mae: 0.3214 - mse: 0.2933 - val_loss: 0.2609 - val_mae: 0.3442 - val_mse: 0.2609
Epoch 3/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2607 - mae: 0.2945 - mse: 0.2607 - val_loss: 0.2064 - val_mae: 0.2063 - val_mse: 0.2064
Epoch 4/100
280/280 [==============================] - 1s 4ms/step - loss: 0.2457 - mae: 0.2785 - mse: 0.2457 - val_loss: 0.2011 - val_mae: 0.2568 - val_mse: 0.2011
Epoch 5/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2412 - mae: 0.2698 - mse: 0.2412 - val_loss: 0.1715 - val_ma

[I 2023-04-27 09:04:22,721] Trial 19 finished with value: 0.18285007178783416 and parameters: {'learning_rate': 0.011180535532260233, 'dropout_rate': 0.025183063885680142, 'num_hidden_layers': 5, 'neurons_per_layer': 193, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'rms'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
1040/1050 [============================>.] - ETA: 0s - loss: 0.3296 - mae: 0.3606 - mse: 0.3296
Epoch: 0, loss:0.3291,  mae:0.3599,  mse:0.3291,  val_loss:0.2326,  val_mae:0.2768,  val_mse:0.2326,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.3291 - mae: 0.3599 - mse: 0.3291 - val_loss: 0.2326 - val_mae: 0.2768 - val_mse: 0.2326
Epoch 2/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2583 - mae: 0.2933 - mse: 0.2583 - val_loss: 0.1980 - val_mae: 0.2464 - val_mse: 0.1980
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2442 - mae: 0.2769 - mse: 0.2442 - val_loss: 0.1928 - val_mae: 0.2368 - val_mse: 0.1928
Epoch 4/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2304 - mae: 0.2635 - mse: 0.2304 - val_loss: 0.1769 - val_mae: 0.2232 - val_mse: 0.1769
Epoch 5/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2232 - mae: 0.2574 - mse: 0.2232 - val_loss: 0.1696 - 

[I 2023-04-27 09:08:03,439] Trial 20 finished with value: 0.12193569540977478 and parameters: {'learning_rate': 0.004865974008872804, 'dropout_rate': 0.041385319263839974, 'num_hidden_layers': 6, 'neurons_per_layer': 230, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
1020/1050 [============================>.] - ETA: 0s - loss: 0.3072 - mae: 0.3369 - mse: 0.3072
Epoch: 0, loss:0.3058,  mae:0.3355,  mse:0.3058,  val_loss:0.2259,  val_mae:0.2756,  val_mse:0.2259,  
1050/1050 [==============================] - 2s 2ms/step - loss: 0.3058 - mae: 0.3355 - mse: 0.3058 - val_loss: 0.2259 - val_mae: 0.2756 - val_mse: 0.2259
Epoch 2/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2491 - mae: 0.2822 - mse: 0.2491 - val_loss: 0.2094 - val_mae: 0.2572 - val_mse: 0.2094
Epoch 3/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2350 - mae: 0.2684 - mse: 0.2350 - val_loss: 0.2014 - val_mae: 0.2385 - val_mse: 0.2014
Epoch 4/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2204 - mae: 0.2527 - mse: 0.2204 - val_loss: 0.1861 - val_mae: 0.2367 - val_mse: 0.1861
Epoch 5/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2094 - mae: 0.2432 - mse: 0.2094 - val_loss: 0.1648 - 

[I 2023-04-27 09:09:46,058] Trial 21 finished with value: 0.12309854999184608 and parameters: {'learning_rate': 0.005515295554875633, 'dropout_rate': 0.011515342412480601, 'num_hidden_layers': 5, 'neurons_per_layer': 101, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
1012/1050 [===========================>..] - ETA: 0s - loss: 0.2869 - mae: 0.3202 - mse: 0.2869
Epoch: 0, loss:0.2860,  mae:0.3189,  mse:0.2860,  val_loss:0.2139,  val_mae:0.2607,  val_mse:0.2139,  
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2860 - mae: 0.3189 - mse: 0.2860 - val_loss: 0.2139 - val_mae: 0.2607 - val_mse: 0.2139
Epoch 2/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2339 - mae: 0.2673 - mse: 0.2339 - val_loss: 0.1900 - val_mae: 0.2364 - val_mse: 0.1900
Epoch 3/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2109 - mae: 0.2453 - mse: 0.2109 - val_loss: 0.1691 - val_mae: 0.2107 - val_mse: 0.1691
Epoch 4/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2028 - mae: 0.2356 - mse: 0.2028 - val_loss: 0.1541 - val_mae: 0.2008 - val_mse: 0.1541
Epoch 5/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.1911 - mae: 0.2260 - mse: 0.1911 - val_loss: 0.1604 - 

[I 2023-04-27 09:10:53,935] Trial 22 finished with value: 0.12658147588372232 and parameters: {'learning_rate': 0.010491177204343533, 'dropout_rate': 0.010986639642530802, 'num_hidden_layers': 4, 'neurons_per_layer': 89, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
1048/1050 [============================>.] - ETA: 0s - loss: 0.3391 - mae: 0.3638 - mse: 0.3391
Epoch: 0, loss:0.3396,  mae:0.3639,  mse:0.3396,  val_loss:0.2404,  val_mae:0.2903,  val_mse:0.2404,  
1050/1050 [==============================] - 3s 2ms/step - loss: 0.3396 - mae: 0.3639 - mse: 0.3396 - val_loss: 0.2404 - val_mae: 0.2903 - val_mse: 0.2404
Epoch 2/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2628 - mae: 0.2961 - mse: 0.2628 - val_loss: 0.2213 - val_mae: 0.2690 - val_mse: 0.2213
Epoch 3/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2522 - mae: 0.2848 - mse: 0.2522 - val_loss: 0.2086 - val_mae: 0.2556 - val_mse: 0.2086
Epoch 4/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2420 - mae: 0.2740 - mse: 0.2420 - val_loss: 0.1959 - val_mae: 0.2440 - val_mse: 0.1959
Epoch 5/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2357 - mae: 0.2698 - mse: 0.2357 - val_loss: 0.1970 - 

[I 2023-04-27 09:13:03,198] Trial 23 finished with value: 0.12112511694431305 and parameters: {'learning_rate': 0.003378163730701339, 'dropout_rate': 0.021421272617592583, 'num_hidden_layers': 5, 'neurons_per_layer': 123, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
280/280 [==============================] - ETA: 0s - loss: 0.3947 - mae: 0.4117 - mse: 0.3947
Epoch: 0, loss:0.3947,  mae:0.4117,  mse:0.3947,  val_loss:0.2945,  val_mae:0.3537,  val_mse:0.2945,  
280/280 [==============================] - 1s 2ms/step - loss: 0.3947 - mae: 0.4117 - mse: 0.3947 - val_loss: 0.2945 - val_mae: 0.3537 - val_mse: 0.2945
Epoch 2/100
280/280 [==============================] - 1s 2ms/step - loss: 0.3050 - mae: 0.3494 - mse: 0.3050 - val_loss: 0.2693 - val_mae: 0.3266 - val_mse: 0.2693
Epoch 3/100
280/280 [==============================] - 1s 2ms/step - loss: 0.2827 - mae: 0.3268 - mse: 0.2827 - val_loss: 0.2547 - val_mae: 0.3082 - val_mse: 0.2547
Epoch 4/100
280/280 [==============================] - 0s 2ms/step - loss: 0.2752 - mae: 0.3154 - mse: 0.2752 - val_loss: 0.2463 - val_mae: 0.2939 - val_mse: 0.2463
Epoch 5/100
280/280 [==============================] - 1s 2ms/step - loss: 0.2657 - mae: 0.3043 - mse: 0.2657 - val_loss: 0.2381 - val_mae: 0.2

280/280 [==============================] - 1s 2ms/step - loss: 0.1811 - mae: 0.2248 - mse: 0.1811 - val_loss: 0.1445 - val_mae: 0.1913 - val_mse: 0.1445
Epoch 99/100
280/280 [==============================] - 0s 2ms/step - loss: 0.1817 - mae: 0.2243 - mse: 0.1817 - val_loss: 0.1443 - val_mae: 0.1932 - val_mse: 0.1443
Epoch 100/100
280/280 [==============================] - 0s 2ms/step - loss: 0.1838 - mae: 0.2269 - mse: 0.1838 - val_loss: 0.1449 - val_mae: 0.1917 - val_mse: 0.1449


[I 2023-04-27 09:13:56,688] Trial 24 finished with value: 0.1458609253168106 and parameters: {'learning_rate': 0.0024729206090521854, 'dropout_rate': 0.021607349049072966, 'num_hidden_layers': 3, 'neurons_per_layer': 135, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
1046/1050 [============================>.] - ETA: 0s - loss: 0.3467 - mae: 0.3729 - mse: 0.3467
Epoch: 0, loss:0.3467,  mae:0.3729,  mse:0.3467,  val_loss:0.2431,  val_mae:0.2895,  val_mse:0.2431,  
1050/1050 [==============================] - 5s 4ms/step - loss: 0.3467 - mae: 0.3729 - mse: 0.3467 - val_loss: 0.2431 - val_mae: 0.2895 - val_mse: 0.2431
Epoch 2/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2611 - mae: 0.2933 - mse: 0.2611 - val_loss: 0.2161 - val_mae: 0.2665 - val_mse: 0.2161
Epoch 3/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2439 - mae: 0.2757 - mse: 0.2439 - val_loss: 0.1982 - val_mae: 0.2494 - val_mse: 0.1982
Epoch 4/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2336 - mae: 0.2668 - mse: 0.2336 - val_loss: 0.1799 - val_mae: 0.2246 - val_mse: 0.1799
Epoch 5/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2236 - mae: 0.2557 - mse: 0.2236 - val_loss: 0.1702 - 

[I 2023-04-27 09:18:18,681] Trial 25 finished with value: 0.11873408779501915 and parameters: {'learning_rate': 0.003780050605552698, 'dropout_rate': 0.026271533315806464, 'num_hidden_layers': 6, 'neurons_per_layer': 263, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
523/525 [============================>.] - ETA: 0s - loss: 0.3233 - mae: 0.3499 - mse: 0.3233
Epoch: 0, loss:0.3229,  mae:0.3497,  mse:0.3229,  val_loss:0.2269,  val_mae:0.2631,  val_mse:0.2269,  
525/525 [==============================] - 3s 5ms/step - loss: 0.3229 - mae: 0.3497 - mse: 0.3229 - val_loss: 0.2269 - val_mae: 0.2631 - val_mse: 0.2269
Epoch 2/100
525/525 [==============================] - 2s 4ms/step - loss: 0.2549 - mae: 0.2850 - mse: 0.2549 - val_loss: 0.2012 - val_mae: 0.2544 - val_mse: 0.2012
Epoch 3/100
525/525 [==============================] - 2s 4ms/step - loss: 0.2359 - mae: 0.2696 - mse: 0.2359 - val_loss: 0.1862 - val_mae: 0.2342 - val_mse: 0.1862
Epoch 4/100
525/525 [==============================] - 2s 4ms/step - loss: 0.2279 - mae: 0.2592 - mse: 0.2279 - val_loss: 0.1643 - val_mae: 0.2149 - val_mse: 0.1643
Epoch 5/100
525/525 [==============================] - 2s 4ms/step - loss: 0.2162 - mae: 0.2488 - mse: 0.2162 - val_loss: 0.1645 - val_mae: 0.2

[I 2023-04-27 09:19:52,164] Trial 26 finished with value: 0.122040393948555 and parameters: {'learning_rate': 0.011580954566719575, 'dropout_rate': 0.035368460726544246, 'num_hidden_layers': 7, 'neurons_per_layer': 270, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
279/280 [============================>.] - ETA: 0s - loss: 0.3259 - mae: 0.3316 - mse: 0.3259
Epoch: 0, loss:0.3255,  mae:0.3314,  mse:0.3255,  val_loss:0.3218,  val_mae:0.3149,  val_mse:0.3218,  
280/280 [==============================] - 2s 5ms/step - loss: 0.3255 - mae: 0.3314 - mse: 0.3255 - val_loss: 0.3218 - val_mae: 0.3149 - val_mse: 0.3218
Epoch 2/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2729 - mae: 0.3027 - mse: 0.2729 - val_loss: 0.2417 - val_mae: 0.3199 - val_mse: 0.2417
Epoch 3/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2659 - mae: 0.2978 - mse: 0.2659 - val_loss: 0.2041 - val_mae: 0.2566 - val_mse: 0.2041
Epoch 4/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2623 - mae: 0.2953 - mse: 0.2623 - val_loss: 0.2301 - val_mae: 0.3066 - val_mse: 0.2301
Epoch 5/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2630 - mae: 0.2905 - mse: 0.2630 - val_loss: 0.2440 - val_mae: 0.2

[I 2023-04-27 09:20:19,048] Trial 27 finished with value: 0.21442948430776596 and parameters: {'learning_rate': 0.00478545166169407, 'dropout_rate': 0.08482646182378697, 'num_hidden_layers': 6, 'neurons_per_layer': 256, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'adam'}. Best is trial 13 with value: 0.11716497093439102.


Epoch 1/100
1050/1050 [==============================] - ETA: 0s - loss: 0.4092 - mae: 0.4296 - mse: 0.4092
Epoch: 0, loss:0.4092,  mae:0.4296,  mse:0.4092,  val_loss:0.2654,  val_mae:0.3225,  val_mse:0.2654,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.4092 - mae: 0.4296 - mse: 0.4092 - val_loss: 0.2654 - val_mae: 0.3225 - val_mse: 0.2654
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2839 - mae: 0.3226 - mse: 0.2839 - val_loss: 0.2291 - val_mae: 0.2825 - val_mse: 0.2291
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2699 - mae: 0.3044 - mse: 0.2699 - val_loss: 0.2169 - val_mae: 0.2719 - val_mse: 0.2169
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2616 - mae: 0.2972 - mse: 0.2616 - val_loss: 0.2063 - val_mae: 0.2603 - val_mse: 0.2063
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2502 - mae: 0.2861 - mse: 0.2502 - val_loss: 0.2005 - 

Epoch 97/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.1553 - mae: 0.1867 - mse: 0.1553 - val_loss: 0.1184 - val_mae: 0.1525 - val_mse: 0.1184


[I 2023-04-27 09:25:15,879] Trial 28 finished with value: 0.116428904235363 and parameters: {'learning_rate': 0.001846690280715085, 'dropout_rate': 0.04420081824199521, 'num_hidden_layers': 6, 'neurons_per_layer': 201, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
1045/1050 [============================>.] - ETA: 0s - loss: 2734910720.0000 - mae: 1696.0485 - mse: 2734910720.0000
Epoch: 0, loss:2721887232.0000,  mae:1687.9753,  mse:2721887232.0000,  val_loss:0.6456,  val_mae:0.6640,  val_mse:0.6456,  
1050/1050 [==============================] - 5s 4ms/step - loss: 2721887232.0000 - mae: 1687.9753 - mse: 2721887232.0000 - val_loss: 0.6456 - val_mae: 0.6640 - val_mse: 0.6456
Epoch 2/100
1050/1050 [==============================] - 4s 4ms/step - loss: 4.9138 - mae: 0.7068 - mse: 4.9138 - val_loss: 0.6454 - val_mae: 0.6526 - val_mse: 0.6454
Epoch 3/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.6559 - mae: 0.6602 - mse: 0.6559 - val_loss: 0.6512 - val_mae: 0.6257 - val_mse: 0.6512
Epoch 4/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.6549 - mae: 0.6595 - mse: 0.6549 - val_loss: 0.6498 - val_mae: 0.6852 - val_mse: 0.6498
Epoch 5/100
1050/1050 [==============================] - 4s 4ms/step -

[I 2023-04-27 09:26:03,088] Trial 29 finished with value: 1.3589812636375427 and parameters: {'learning_rate': 0.04483592239141943, 'dropout_rate': 0.048201302168258874, 'num_hidden_layers': 7, 'neurons_per_layer': 200, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'rms'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
258/280 [==========================>...] - ETA: 0s - loss: 0.2724 - mae: 0.2869 - mse: 0.2724
Epoch: 0, loss:0.2680,  mae:0.2837,  mse:0.2680,  val_loss:0.1893,  val_mae:0.2270,  val_mse:0.1893,  
280/280 [==============================] - 1s 3ms/step - loss: 0.2680 - mae: 0.2837 - mse: 0.2680 - val_loss: 0.1893 - val_mae: 0.2270 - val_mse: 0.1893
Epoch 2/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2146 - mae: 0.2378 - mse: 0.2146 - val_loss: 0.1621 - val_mae: 0.2083 - val_mse: 0.1621
Epoch 3/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2058 - mae: 0.2292 - mse: 0.2058 - val_loss: 0.1637 - val_mae: 0.2106 - val_mse: 0.1637
Epoch 4/100
280/280 [==============================] - 1s 3ms/step - loss: 0.1939 - mae: 0.2212 - mse: 0.1939 - val_loss: 0.1841 - val_mae: 0.2012 - val_mse: 0.1841
Epoch 5/100
280/280 [==============================] - 1s 3ms/step - loss: 0.1883 - mae: 0.2135 - mse: 0.1883 - val_loss: 0.1494 - val_mae: 0.1

[I 2023-04-27 09:26:26,295] Trial 30 finished with value: 0.1283658564090729 and parameters: {'learning_rate': 0.0018833815076202856, 'dropout_rate': 0.015772835305649536, 'num_hidden_layers': 5, 'neurons_per_layer': 169, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'adam'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
1049/1050 [============================>.] - ETA: 0s - loss: 0.3097 - mae: 0.3438 - mse: 0.3097
Epoch: 0, loss:0.3096,  mae:0.3437,  mse:0.3096,  val_loss:0.2219,  val_mae:0.2648,  val_mse:0.2219,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.3096 - mae: 0.3437 - mse: 0.3096 - val_loss: 0.2219 - val_mae: 0.2648 - val_mse: 0.2219
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2553 - mae: 0.2866 - mse: 0.2553 - val_loss: 0.1983 - val_mae: 0.2520 - val_mse: 0.1983
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2352 - mae: 0.2683 - mse: 0.2352 - val_loss: 0.1869 - val_mae: 0.2364 - val_mse: 0.1869
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2224 - mae: 0.2549 - mse: 0.2224 - val_loss: 0.1688 - val_mae: 0.2166 - val_mse: 0.1688
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2131 - mae: 0.2457 - mse: 0.2131 - val_loss: 0.1623 - 

[I 2023-04-27 09:29:28,701] Trial 31 finished with value: 0.11955458596348763 and parameters: {'learning_rate': 0.0070630104886147205, 'dropout_rate': 0.03123595432502256, 'num_hidden_layers': 6, 'neurons_per_layer': 223, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
1040/1050 [============================>.] - ETA: 0s - loss: 0.4346 - mae: 0.4517 - mse: 0.4346
Epoch: 0, loss:0.4334,  mae:0.4508,  mse:0.4334,  val_loss:0.2725,  val_mae:0.3248,  val_mse:0.2725,  
1050/1050 [==============================] - 5s 4ms/step - loss: 0.4334 - mae: 0.4508 - mse: 0.4334 - val_loss: 0.2725 - val_mae: 0.3248 - val_mse: 0.2725
Epoch 2/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2894 - mae: 0.3255 - mse: 0.2894 - val_loss: 0.2481 - val_mae: 0.3003 - val_mse: 0.2481
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2740 - mae: 0.3095 - mse: 0.2740 - val_loss: 0.2344 - val_mae: 0.2828 - val_mse: 0.2344
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2659 - mae: 0.3023 - mse: 0.2659 - val_loss: 0.2295 - val_mae: 0.2758 - val_mse: 0.2295
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2610 - mae: 0.2958 - mse: 0.2610 - val_loss: 0.2180 - 

[I 2023-04-27 09:34:49,541] Trial 32 finished with value: 0.12101069539785385 and parameters: {'learning_rate': 0.0012076132670380839, 'dropout_rate': 0.04317870751248888, 'num_hidden_layers': 6, 'neurons_per_layer': 257, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
1016/1050 [============================>.] - ETA: 0s - loss: 0.3551 - mae: 0.3788 - mse: 0.3551
Epoch: 0, loss:0.3529,  mae:0.3772,  mse:0.3529,  val_loss:0.2593,  val_mae:0.3098,  val_mse:0.2593,  
1050/1050 [==============================] - 3s 2ms/step - loss: 0.3529 - mae: 0.3772 - mse: 0.3529 - val_loss: 0.2593 - val_mae: 0.3098 - val_mse: 0.2593
Epoch 2/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2847 - mae: 0.3201 - mse: 0.2847 - val_loss: 0.2249 - val_mae: 0.2756 - val_mse: 0.2249
Epoch 3/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2680 - mae: 0.3046 - mse: 0.2680 - val_loss: 0.2115 - val_mae: 0.2600 - val_mse: 0.2115
Epoch 4/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2551 - mae: 0.2935 - mse: 0.2551 - val_loss: 0.1943 - val_mae: 0.2379 - val_mse: 0.1943
Epoch 5/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2475 - mae: 0.2852 - mse: 0.2475 - val_loss: 0.1840 - 

[I 2023-04-27 09:37:48,147] Trial 33 finished with value: 0.12348831370472908 and parameters: {'learning_rate': 0.004518121642259178, 'dropout_rate': 0.06411317204783987, 'num_hidden_layers': 6, 'neurons_per_layer': 154, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
837/840 [============================>.] - ETA: 0s - loss: 0.2843 - mae: 0.3166 - mse: 0.2843
Epoch: 0, loss:0.2842,  mae:0.3166,  mse:0.2842,  val_loss:0.2004,  val_mae:0.2474,  val_mse:0.2004,  
840/840 [==============================] - 4s 4ms/step - loss: 0.2842 - mae: 0.3166 - mse: 0.2842 - val_loss: 0.2004 - val_mae: 0.2474 - val_mse: 0.2004
Epoch 2/100
840/840 [==============================] - 3s 3ms/step - loss: 0.2373 - mae: 0.2691 - mse: 0.2373 - val_loss: 0.1774 - val_mae: 0.2288 - val_mse: 0.1774
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2177 - mae: 0.2526 - mse: 0.2177 - val_loss: 0.1793 - val_mae: 0.2266 - val_mse: 0.1793
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2082 - mae: 0.2436 - mse: 0.2082 - val_loss: 0.1938 - val_mae: 0.2272 - val_mse: 0.1938
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.1968 - mae: 0.2297 - mse: 0.1968 - val_loss: 0.1680 - val_mae: 0.2

[I 2023-04-27 09:38:47,964] Trial 34 finished with value: 0.12422742024064064 and parameters: {'learning_rate': 0.015189096815514534, 'dropout_rate': 0.02514472641021129, 'num_hidden_layers': 5, 'neurons_per_layer': 183, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
1043/1050 [============================>.] - ETA: 0s - loss: 0.4829 - mae: 0.4902 - mse: 0.4829
Epoch: 0, loss:0.4815,  mae:0.4894,  mse:0.4815,  val_loss:0.2893,  val_mae:0.3470,  val_mse:0.2893,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.4815 - mae: 0.4894 - mse: 0.4815 - val_loss: 0.2893 - val_mae: 0.3470 - val_mse: 0.2893
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.3019 - mae: 0.3392 - mse: 0.3019 - val_loss: 0.2470 - val_mae: 0.3017 - val_mse: 0.2470
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2784 - mae: 0.3140 - mse: 0.2784 - val_loss: 0.2285 - val_mae: 0.2805 - val_mse: 0.2285
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2690 - mae: 0.3038 - mse: 0.2690 - val_loss: 0.2167 - val_mae: 0.2675 - val_mse: 0.2167
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2629 - mae: 0.2981 - mse: 0.2629 - val_loss: 0.2094 - 

Epoch 97/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.1632 - mae: 0.1944 - mse: 0.1632 - val_loss: 0.1182 - val_mae: 0.1513 - val_mse: 0.1182
Epoch 98/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.1656 - mae: 0.1946 - mse: 0.1656 - val_loss: 0.1207 - val_mae: 0.1535 - val_mse: 0.1207
Epoch 99/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.1592 - mae: 0.1941 - mse: 0.1592 - val_loss: 0.1170 - val_mae: 0.1530 - val_mse: 0.1170
Epoch 100/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.1624 - mae: 0.1936 - mse: 0.1624 - val_loss: 0.1239 - val_mae: 0.1558 - val_mse: 0.1239


[I 2023-04-27 09:44:04,629] Trial 35 finished with value: 0.12055784165859222 and parameters: {'learning_rate': 0.0013299744590639499, 'dropout_rate': 0.04794694140206751, 'num_hidden_layers': 7, 'neurons_per_layer': 219, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
1049/1050 [============================>.] - ETA: 0s - loss: 0.3708 - mae: 0.3967 - mse: 0.3708
Epoch: 0, loss:0.3709,  mae:0.3966,  mse:0.3709,  val_loss:0.2525,  val_mae:0.3043,  val_mse:0.2525,  
1050/1050 [==============================] - 3s 2ms/step - loss: 0.3709 - mae: 0.3966 - mse: 0.3709 - val_loss: 0.2525 - val_mae: 0.3043 - val_mse: 0.2525
Epoch 2/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2635 - mae: 0.2990 - mse: 0.2635 - val_loss: 0.2249 - val_mae: 0.2720 - val_mse: 0.2249
Epoch 3/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2508 - mae: 0.2867 - mse: 0.2508 - val_loss: 0.2144 - val_mae: 0.2590 - val_mse: 0.2144
Epoch 4/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2370 - mae: 0.2736 - mse: 0.2370 - val_loss: 0.1983 - val_mae: 0.2480 - val_mse: 0.1983
Epoch 5/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2319 - mae: 0.2681 - mse: 0.2319 - val_loss: 0.1948 - 

[I 2023-04-27 09:47:20,034] Trial 36 finished with value: 0.11960459947586059 and parameters: {'learning_rate': 0.0023190718238339414, 'dropout_rate': 0.015239111678298792, 'num_hidden_layers': 6, 'neurons_per_layer': 147, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
409/420 [============================>.] - ETA: 0s - loss: 0.3206 - mae: 0.3081 - mse: 0.3206
Epoch: 0, loss:0.3180,  mae:0.3063,  mse:0.3180,  val_loss:0.2158,  val_mae:0.2332,  val_mse:0.2158,  
420/420 [==============================] - 2s 3ms/step - loss: 0.3180 - mae: 0.3063 - mse: 0.3180 - val_loss: 0.2158 - val_mae: 0.2332 - val_mse: 0.2158
Epoch 2/100
420/420 [==============================] - 1s 3ms/step - loss: 0.2494 - mae: 0.2656 - mse: 0.2494 - val_loss: 0.1999 - val_mae: 0.2623 - val_mse: 0.1999
Epoch 3/100
420/420 [==============================] - 1s 3ms/step - loss: 0.2232 - mae: 0.2500 - mse: 0.2232 - val_loss: 0.1534 - val_mae: 0.2059 - val_mse: 0.1534
Epoch 4/100
420/420 [==============================] - 1s 3ms/step - loss: 0.2193 - mae: 0.2447 - mse: 0.2193 - val_loss: 0.1794 - val_mae: 0.2169 - val_mse: 0.1794
Epoch 5/100
420/420 [==============================] - 1s 3ms/step - loss: 0.2178 - mae: 0.2472 - mse: 0.2178 - val_loss: 0.1852 - val_mae: 0.2

[I 2023-04-27 09:48:20,030] Trial 37 finished with value: 0.14366333782672883 and parameters: {'learning_rate': 0.0035416314299036374, 'dropout_rate': 0.05665215980061426, 'num_hidden_layers': 3, 'neurons_per_layer': 249, 'batch_size': 20, 'activation': 'relu', 'optimizer': 'rms'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
831/840 [============================>.] - ETA: 0s - loss: 0.3211 - mae: 0.3554 - mse: 0.3211
Epoch: 0, loss:0.3217,  mae:0.3555,  mse:0.3217,  val_loss:0.2351,  val_mae:0.2886,  val_mse:0.2351,  
840/840 [==============================] - 2s 2ms/step - loss: 0.3217 - mae: 0.3555 - mse: 0.3217 - val_loss: 0.2351 - val_mae: 0.2886 - val_mse: 0.2351
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2743 - mae: 0.3088 - mse: 0.2743 - val_loss: 0.2174 - val_mae: 0.2681 - val_mse: 0.2174
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2613 - mae: 0.2960 - mse: 0.2613 - val_loss: 0.2057 - val_mae: 0.2630 - val_mse: 0.2057
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2493 - mae: 0.2861 - mse: 0.2493 - val_loss: 0.1892 - val_mae: 0.2415 - val_mse: 0.1892
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2456 - mae: 0.2826 - mse: 0.2456 - val_loss: 0.1792 - val_mae: 0.2

[I 2023-04-27 09:50:12,462] Trial 38 finished with value: 0.12971632704138755 and parameters: {'learning_rate': 0.007342330114255564, 'dropout_rate': 0.07985620688352466, 'num_hidden_layers': 4, 'neurons_per_layer': 211, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
511/525 [============================>.] - ETA: 0s - loss: 0.2716 - mae: 0.2892 - mse: 0.2716
Epoch: 0, loss:0.2688,  mae:0.2875,  mse:0.2688,  val_loss:0.1972,  val_mae:0.2379,  val_mse:0.1972,  
525/525 [==============================] - 3s 4ms/step - loss: 0.2688 - mae: 0.2875 - mse: 0.2688 - val_loss: 0.1972 - val_mae: 0.2379 - val_mse: 0.1972
Epoch 2/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2268 - mae: 0.2500 - mse: 0.2268 - val_loss: 0.1607 - val_mae: 0.1998 - val_mse: 0.1607
Epoch 3/100
525/525 [==============================] - 2s 3ms/step - loss: 0.1997 - mae: 0.2243 - mse: 0.1997 - val_loss: 0.1466 - val_mae: 0.1866 - val_mse: 0.1466
Epoch 4/100
525/525 [==============================] - 2s 3ms/step - loss: 0.1872 - mae: 0.2108 - mse: 0.1872 - val_loss: 0.1640 - val_mae: 0.2044 - val_mse: 0.1640
Epoch 5/100
525/525 [==============================] - 2s 3ms/step - loss: 0.1809 - mae: 0.2054 - mse: 0.1809 - val_loss: 0.1571 - val_mae: 0.1

[I 2023-04-27 09:50:57,223] Trial 39 finished with value: 0.13738201931118965 and parameters: {'learning_rate': 0.0019606293341901206, 'dropout_rate': 0.019260359168915685, 'num_hidden_layers': 4, 'neurons_per_layer': 75, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'adam'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
1037/1050 [============================>.] - ETA: 0s - loss: 0.4916 - mae: 0.5015 - mse: 0.4916
Epoch: 0, loss:0.4895,  mae:0.5003,  mse:0.4895,  val_loss:0.2924,  val_mae:0.3586,  val_mse:0.2924,  
1050/1050 [==============================] - 3s 3ms/step - loss: 0.4895 - mae: 0.5003 - mse: 0.4895 - val_loss: 0.2924 - val_mae: 0.3586 - val_mse: 0.2924
Epoch 2/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.3009 - mae: 0.3461 - mse: 0.3009 - val_loss: 0.2576 - val_mae: 0.3164 - val_mse: 0.2576
Epoch 3/100
1050/1050 [==============================] - 3s 2ms/step - loss: 0.2839 - mae: 0.3240 - mse: 0.2839 - val_loss: 0.2418 - val_mae: 0.2973 - val_mse: 0.2418
Epoch 4/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2730 - mae: 0.3120 - mse: 0.2730 - val_loss: 0.2271 - val_mae: 0.2801 - val_mse: 0.2271
Epoch 5/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.2682 - mae: 0.3052 - mse: 0.2682 - val_loss: 0.2197 - 

Epoch 97/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.1685 - mae: 0.2020 - mse: 0.1685 - val_loss: 0.1220 - val_mae: 0.1591 - val_mse: 0.1220
Epoch 98/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.1638 - mae: 0.1974 - mse: 0.1638 - val_loss: 0.1203 - val_mae: 0.1601 - val_mse: 0.1203
Epoch 99/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.1681 - mae: 0.2008 - mse: 0.1681 - val_loss: 0.1239 - val_mae: 0.1572 - val_mse: 0.1239
Epoch 100/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.1657 - mae: 0.1994 - mse: 0.1657 - val_loss: 0.1208 - val_mae: 0.1584 - val_mse: 0.1208


[I 2023-04-27 09:55:31,141] Trial 40 finished with value: 0.12423942610621452 and parameters: {'learning_rate': 0.0010031123070383208, 'dropout_rate': 0.041771092513687096, 'num_hidden_layers': 6, 'neurons_per_layer': 190, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
1040/1050 [============================>.] - ETA: 0s - loss: 0.3186 - mae: 0.3462 - mse: 0.3186
Epoch: 0, loss:0.3192,  mae:0.3460,  mse:0.3192,  val_loss:0.2212,  val_mae:0.2731,  val_mse:0.2212,  
1050/1050 [==============================] - 5s 4ms/step - loss: 0.3192 - mae: 0.3460 - mse: 0.3192 - val_loss: 0.2212 - val_mae: 0.2731 - val_mse: 0.2212
Epoch 2/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2401 - mae: 0.2738 - mse: 0.2401 - val_loss: 0.1881 - val_mae: 0.2382 - val_mse: 0.1881
Epoch 3/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2243 - mae: 0.2583 - mse: 0.2243 - val_loss: 0.1766 - val_mae: 0.2357 - val_mse: 0.1766
Epoch 4/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2087 - mae: 0.2448 - mse: 0.2087 - val_loss: 0.1632 - val_mae: 0.2020 - val_mse: 0.1632
Epoch 5/100
1050/1050 [==============================] - 5s 5ms/step - loss: 0.2055 - mae: 0.2391 - mse: 0.2055 - val_loss: 0.1592 - 

[I 2023-04-27 09:58:13,081] Trial 41 finished with value: 0.12158090770244598 and parameters: {'learning_rate': 0.007807290329931255, 'dropout_rate': 0.02807855095125007, 'num_hidden_layers': 6, 'neurons_per_layer': 283, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 28 with value: 0.116428904235363.


Epoch 1/100
1031/1050 [============================>.] - ETA: 0s - loss: 0.3286 - mae: 0.3587 - mse: 0.3286
Epoch: 0, loss:0.3297,  mae:0.3590,  mse:0.3297,  val_loss:0.2400,  val_mae:0.2859,  val_mse:0.2400,  
1050/1050 [==============================] - 3s 3ms/step - loss: 0.3297 - mae: 0.3590 - mse: 0.3297 - val_loss: 0.2400 - val_mae: 0.2859 - val_mse: 0.2400
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2654 - mae: 0.2965 - mse: 0.2654 - val_loss: 0.2210 - val_mae: 0.2748 - val_mse: 0.2210
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2484 - mae: 0.2829 - mse: 0.2484 - val_loss: 0.2073 - val_mae: 0.2631 - val_mse: 0.2073
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2363 - mae: 0.2715 - mse: 0.2363 - val_loss: 0.1933 - val_mae: 0.2488 - val_mse: 0.1933
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2266 - mae: 0.2648 - mse: 0.2266 - val_loss: 0.1900 - 

[I 2023-04-27 10:02:40,497] Trial 42 finished with value: 0.11590382903814316 and parameters: {'learning_rate': 0.0037768035036120588, 'dropout_rate': 0.0293501175504138, 'num_hidden_layers': 5, 'neurons_per_layer': 220, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 42 with value: 0.11590382903814316.


Epoch 1/100
1045/1050 [============================>.] - ETA: 0s - loss: 0.3249 - mae: 0.3528 - mse: 0.3249
Epoch: 0, loss:0.3243,  mae:0.3523,  mse:0.3243,  val_loss:0.2438,  val_mae:0.2854,  val_mse:0.2438,  
1050/1050 [==============================] - 4s 4ms/step - loss: 0.3243 - mae: 0.3523 - mse: 0.3243 - val_loss: 0.2438 - val_mae: 0.2854 - val_mse: 0.2438
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2699 - mae: 0.2989 - mse: 0.2699 - val_loss: 0.2303 - val_mae: 0.2780 - val_mse: 0.2303
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2534 - mae: 0.2859 - mse: 0.2534 - val_loss: 0.2165 - val_mae: 0.2610 - val_mse: 0.2165
Epoch 4/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2442 - mae: 0.2777 - mse: 0.2442 - val_loss: 0.1952 - val_mae: 0.2429 - val_mse: 0.1952
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2338 - mae: 0.2700 - mse: 0.2338 - val_loss: 0.1809 - 

[I 2023-04-27 10:05:49,691] Trial 43 finished with value: 0.11898797452449798 and parameters: {'learning_rate': 0.004083683049681904, 'dropout_rate': 0.03624033018404103, 'num_hidden_layers': 5, 'neurons_per_layer': 269, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 42 with value: 0.11590382903814316.


Epoch 1/100
1042/1050 [============================>.] - ETA: 0s - loss: 0.3631 - mae: 0.3860 - mse: 0.3631
Epoch: 0, loss:0.3616,  mae:0.3850,  mse:0.3616,  val_loss:0.2495,  val_mae:0.3072,  val_mse:0.2495,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.3616 - mae: 0.3850 - mse: 0.3616 - val_loss: 0.2495 - val_mae: 0.3072 - val_mse: 0.2495
Epoch 2/100
1050/1050 [==============================] - 3s 2ms/step - loss: 0.2743 - mae: 0.3113 - mse: 0.2743 - val_loss: 0.2304 - val_mae: 0.2794 - val_mse: 0.2304
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2652 - mae: 0.2989 - mse: 0.2652 - val_loss: 0.2189 - val_mae: 0.2688 - val_mse: 0.2189
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2581 - mae: 0.2923 - mse: 0.2581 - val_loss: 0.2098 - val_mae: 0.2619 - val_mse: 0.2098
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2511 - mae: 0.2881 - mse: 0.2511 - val_loss: 0.1996 - 

[I 2023-04-27 10:09:16,057] Trial 44 finished with value: 0.12967752367258073 and parameters: {'learning_rate': 0.003112338606179763, 'dropout_rate': 0.05560182037423186, 'num_hidden_layers': 5, 'neurons_per_layer': 246, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 42 with value: 0.11590382903814316.


Epoch 1/100
406/420 [============================>.] - ETA: 0s - loss: 0.4617 - mae: 0.4621 - mse: 0.4617
Epoch: 0, loss:0.4565,  mae:0.4585,  mse:0.4565,  val_loss:0.2877,  val_mae:0.3564,  val_mse:0.2877,  
420/420 [==============================] - 2s 4ms/step - loss: 0.4565 - mae: 0.4585 - mse: 0.4565 - val_loss: 0.2877 - val_mae: 0.3564 - val_mse: 0.2877
Epoch 2/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2922 - mae: 0.3427 - mse: 0.2922 - val_loss: 0.2562 - val_mae: 0.3193 - val_mse: 0.2562
Epoch 3/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2766 - mae: 0.3178 - mse: 0.2766 - val_loss: 0.2421 - val_mae: 0.2972 - val_mse: 0.2421
Epoch 4/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2643 - mae: 0.3032 - mse: 0.2643 - val_loss: 0.2335 - val_mae: 0.2865 - val_mse: 0.2335
Epoch 5/100
420/420 [==============================] - 1s 2ms/step - loss: 0.2633 - mae: 0.2982 - mse: 0.2633 - val_loss: 0.2263 - val_mae: 0.2

420/420 [==============================] - 2s 4ms/step - loss: 0.1616 - mae: 0.1988 - mse: 0.1616 - val_loss: 0.1275 - val_mae: 0.1675 - val_mse: 0.1275
Epoch 99/100
420/420 [==============================] - 1s 3ms/step - loss: 0.1613 - mae: 0.1999 - mse: 0.1613 - val_loss: 0.1266 - val_mae: 0.1673 - val_mse: 0.1266
Epoch 100/100
420/420 [==============================] - 1s 3ms/step - loss: 0.1620 - mae: 0.1977 - mse: 0.1620 - val_loss: 0.1275 - val_mae: 0.1699 - val_mse: 0.1275


[I 2023-04-27 10:10:36,637] Trial 45 finished with value: 0.12860662937164308 and parameters: {'learning_rate': 0.0026146709837084623, 'dropout_rate': 0.022610013360555535, 'num_hidden_layers': 4, 'neurons_per_layer': 161, 'batch_size': 20, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 42 with value: 0.11590382903814316.


Epoch 1/100
274/280 [============================>.] - ETA: 0s - loss: 0.4997 - mae: 0.3485 - mse: 0.4997
Epoch: 0, loss:0.4945,  mae:0.3474,  mse:0.4945,  val_loss:0.2135,  val_mae:0.2566,  val_mse:0.2135,  
280/280 [==============================] - 4s 7ms/step - loss: 0.4945 - mae: 0.3474 - mse: 0.4945 - val_loss: 0.2135 - val_mae: 0.2566 - val_mse: 0.2135
Epoch 2/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2387 - mae: 0.2659 - mse: 0.2387 - val_loss: 0.2166 - val_mae: 0.2422 - val_mse: 0.2166
Epoch 3/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2324 - mae: 0.2590 - mse: 0.2324 - val_loss: 0.2063 - val_mae: 0.2528 - val_mse: 0.2063
Epoch 4/100
280/280 [==============================] - 1s 4ms/step - loss: 0.2280 - mae: 0.2599 - mse: 0.2280 - val_loss: 0.1942 - val_mae: 0.2673 - val_mse: 0.1942
Epoch 5/100
280/280 [==============================] - 1s 5ms/step - loss: 0.2168 - mae: 0.2519 - mse: 0.2168 - val_loss: 0.1702 - val_mae: 0.2

[I 2023-04-27 10:11:18,563] Trial 46 finished with value: 0.14679894745349883 and parameters: {'learning_rate': 0.005947252444512877, 'dropout_rate': 0.02979814726714357, 'num_hidden_layers': 4, 'neurons_per_layer': 212, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'rms'}. Best is trial 42 with value: 0.11590382903814316.


Epoch 1/100
827/840 [============================>.] - ETA: 0s - loss: 0.3451 - mae: 0.3757 - mse: 0.3451
Epoch: 0, loss:0.3441,  mae:0.3748,  mse:0.3441,  val_loss:0.2480,  val_mae:0.2954,  val_mse:0.2480,  
840/840 [==============================] - 3s 3ms/step - loss: 0.3441 - mae: 0.3748 - mse: 0.3441 - val_loss: 0.2480 - val_mae: 0.2954 - val_mse: 0.2480
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2663 - mae: 0.3013 - mse: 0.2663 - val_loss: 0.2273 - val_mae: 0.2715 - val_mse: 0.2273
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2529 - mae: 0.2867 - mse: 0.2529 - val_loss: 0.2125 - val_mae: 0.2490 - val_mse: 0.2125
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2423 - mae: 0.2744 - mse: 0.2423 - val_loss: 0.2002 - val_mae: 0.2462 - val_mse: 0.2002
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2339 - mae: 0.2697 - mse: 0.2339 - val_loss: 0.1888 - val_mae: 0.2

[I 2023-04-27 10:14:13,914] Trial 47 finished with value: 0.11566240414977073 and parameters: {'learning_rate': 0.004085847461567881, 'dropout_rate': 0.02042413513036418, 'num_hidden_layers': 5, 'neurons_per_layer': 199, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 47 with value: 0.11566240414977073.


Epoch 1/100
834/840 [============================>.] - ETA: 0s - loss: 0.4018 - mae: 0.4260 - mse: 0.4018
Epoch: 0, loss:0.4001,  mae:0.4248,  mse:0.4001,  val_loss:0.2876,  val_mae:0.3422,  val_mse:0.2876,  
840/840 [==============================] - 2s 2ms/step - loss: 0.4001 - mae: 0.4248 - mse: 0.4001 - val_loss: 0.2876 - val_mae: 0.3422 - val_mse: 0.2876
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2960 - mae: 0.3335 - mse: 0.2960 - val_loss: 0.2612 - val_mae: 0.3153 - val_mse: 0.2612
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2803 - mae: 0.3159 - mse: 0.2803 - val_loss: 0.2455 - val_mae: 0.2961 - val_mse: 0.2455
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2682 - mae: 0.3028 - mse: 0.2682 - val_loss: 0.2389 - val_mae: 0.2882 - val_mse: 0.2389
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2631 - mae: 0.2959 - mse: 0.2631 - val_loss: 0.2259 - val_mae: 0.2

840/840 [==============================] - 2s 2ms/step - loss: 0.1471 - mae: 0.1870 - mse: 0.1471 - val_loss: 0.1218 - val_mae: 0.1598 - val_mse: 0.1218
Epoch 99/100
840/840 [==============================] - 2s 2ms/step - loss: 0.1497 - mae: 0.1882 - mse: 0.1497 - val_loss: 0.1245 - val_mae: 0.1642 - val_mse: 0.1245
Epoch 100/100
840/840 [==============================] - 2s 3ms/step - loss: 0.1475 - mae: 0.1884 - mse: 0.1475 - val_loss: 0.1233 - val_mae: 0.1644 - val_mse: 0.1233


[I 2023-04-27 10:17:10,072] Trial 48 finished with value: 0.12224975675344467 and parameters: {'learning_rate': 0.0015070974167509337, 'dropout_rate': 0.018192217262427375, 'num_hidden_layers': 5, 'neurons_per_layer': 175, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 47 with value: 0.11566240414977073.


Epoch 1/100
826/840 [============================>.] - ETA: 0s - loss: 0.3943 - mae: 0.4217 - mse: 0.3943
Epoch: 0, loss:0.3948,  mae:0.4211,  mse:0.3948,  val_loss:0.2737,  val_mae:0.3368,  val_mse:0.2737,  
840/840 [==============================] - 2s 2ms/step - loss: 0.3948 - mae: 0.4211 - mse: 0.3948 - val_loss: 0.2737 - val_mae: 0.3368 - val_mse: 0.2737
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2824 - mae: 0.3272 - mse: 0.2824 - val_loss: 0.2430 - val_mae: 0.3005 - val_mse: 0.2430
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2656 - mae: 0.3058 - mse: 0.2656 - val_loss: 0.2295 - val_mae: 0.2824 - val_mse: 0.2295
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2562 - mae: 0.2933 - mse: 0.2562 - val_loss: 0.2209 - val_mae: 0.2738 - val_mse: 0.2209
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2531 - mae: 0.2873 - mse: 0.2531 - val_loss: 0.2138 - val_mae: 0.2

840/840 [==============================] - 2s 2ms/step - loss: 0.1519 - mae: 0.1830 - mse: 0.1519 - val_loss: 0.1204 - val_mae: 0.1571 - val_mse: 0.1204
Epoch 99/100
840/840 [==============================] - 2s 2ms/step - loss: 0.1469 - mae: 0.1807 - mse: 0.1469 - val_loss: 0.1223 - val_mae: 0.1603 - val_mse: 0.1223
Epoch 100/100
840/840 [==============================] - 1s 2ms/step - loss: 0.1456 - mae: 0.1797 - mse: 0.1456 - val_loss: 0.1176 - val_mae: 0.1576 - val_mse: 0.1176


[I 2023-04-27 10:19:40,359] Trial 49 finished with value: 0.12079729810357094 and parameters: {'learning_rate': 0.0016380749255231143, 'dropout_rate': 0.013458784200225286, 'num_hidden_layers': 5, 'neurons_per_layer': 134, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 47 with value: 0.11566240414977073.


Epoch 1/100
824/840 [============================>.] - ETA: 0s - loss: 0.2661 - mae: 0.2825 - mse: 0.2661
Epoch: 0, loss:0.2644,  mae:0.2809,  mse:0.2644,  val_loss:0.1760,  val_mae:0.2069,  val_mse:0.1760,  
840/840 [==============================] - 2s 2ms/step - loss: 0.2644 - mae: 0.2809 - mse: 0.2644 - val_loss: 0.1760 - val_mae: 0.2069 - val_mse: 0.1760
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2196 - mae: 0.2420 - mse: 0.2196 - val_loss: 0.1640 - val_mae: 0.2154 - val_mse: 0.1640
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2027 - mae: 0.2268 - mse: 0.2027 - val_loss: 0.1510 - val_mae: 0.2069 - val_mse: 0.1510
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.1932 - mae: 0.2204 - mse: 0.1932 - val_loss: 0.1744 - val_mae: 0.2194 - val_mse: 0.1744
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.1887 - mae: 0.2130 - mse: 0.1887 - val_loss: 0.1398 - val_mae: 0.1

[I 2023-04-27 10:20:48,788] Trial 50 finished with value: 0.14393194541335105 and parameters: {'learning_rate': 0.0024302320969394353, 'dropout_rate': 0.016723128152559892, 'num_hidden_layers': 3, 'neurons_per_layer': 199, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'adam'}. Best is trial 47 with value: 0.11566240414977073.


Epoch 1/100
840/840 [==============================] - ETA: 0s - loss: 0.3599 - mae: 0.3920 - mse: 0.3599
Epoch: 0, loss:0.3599,  mae:0.3920,  mse:0.3599,  val_loss:0.2541,  val_mae:0.3045,  val_mse:0.2541,  
840/840 [==============================] - 4s 3ms/step - loss: 0.3599 - mae: 0.3920 - mse: 0.3599 - val_loss: 0.2541 - val_mae: 0.3045 - val_mse: 0.2541
Epoch 2/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2752 - mae: 0.3091 - mse: 0.2752 - val_loss: 0.2271 - val_mae: 0.2718 - val_mse: 0.2271
Epoch 3/100
840/840 [==============================] - 3s 3ms/step - loss: 0.2558 - mae: 0.2902 - mse: 0.2558 - val_loss: 0.2112 - val_mae: 0.2588 - val_mse: 0.2112
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2485 - mae: 0.2839 - mse: 0.2485 - val_loss: 0.1997 - val_mae: 0.2497 - val_mse: 0.1997
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2367 - mae: 0.2717 - mse: 0.2367 - val_loss: 0.1918 - val_mae: 0.2

[I 2023-04-27 10:23:54,713] Trial 51 finished with value: 0.11688227280974388 and parameters: {'learning_rate': 0.0035301783533597643, 'dropout_rate': 0.02817002299207731, 'num_hidden_layers': 5, 'neurons_per_layer': 225, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 47 with value: 0.11566240414977073.


Epoch 1/100
829/840 [============================>.] - ETA: 0s - loss: 0.3316 - mae: 0.3613 - mse: 0.3316
Epoch: 0, loss:0.3320,  mae:0.3614,  mse:0.3320,  val_loss:0.2389,  val_mae:0.2896,  val_mse:0.2389,  
840/840 [==============================] - 3s 3ms/step - loss: 0.3320 - mae: 0.3614 - mse: 0.3320 - val_loss: 0.2389 - val_mae: 0.2896 - val_mse: 0.2389
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2655 - mae: 0.3000 - mse: 0.2655 - val_loss: 0.2272 - val_mae: 0.2732 - val_mse: 0.2272
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2501 - mae: 0.2854 - mse: 0.2501 - val_loss: 0.2011 - val_mae: 0.2458 - val_mse: 0.2011
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2387 - mae: 0.2730 - mse: 0.2387 - val_loss: 0.2015 - val_mae: 0.2434 - val_mse: 0.2015
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2314 - mae: 0.2633 - mse: 0.2314 - val_loss: 0.1898 - val_mae: 0.2

[I 2023-04-27 10:26:52,825] Trial 52 finished with value: 0.11352565735578538 and parameters: {'learning_rate': 0.0043152717234109655, 'dropout_rate': 0.03272936490580361, 'num_hidden_layers': 5, 'neurons_per_layer': 240, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 52 with value: 0.11352565735578538.


Epoch 1/100
822/840 [============================>.] - ETA: 0s - loss: 0.3317 - mae: 0.3658 - mse: 0.3317
Epoch: 0, loss:0.3336,  mae:0.3656,  mse:0.3336,  val_loss:0.2442,  val_mae:0.2964,  val_mse:0.2442,  
840/840 [==============================] - 2s 2ms/step - loss: 0.3336 - mae: 0.3656 - mse: 0.3336 - val_loss: 0.2442 - val_mae: 0.2964 - val_mse: 0.2442
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2651 - mae: 0.3010 - mse: 0.2651 - val_loss: 0.2248 - val_mae: 0.2736 - val_mse: 0.2248
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2575 - mae: 0.2917 - mse: 0.2575 - val_loss: 0.2148 - val_mae: 0.2648 - val_mse: 0.2148
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2510 - mae: 0.2854 - mse: 0.2510 - val_loss: 0.2075 - val_mae: 0.2575 - val_mse: 0.2075
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2453 - mae: 0.2803 - mse: 0.2453 - val_loss: 0.2004 - val_mae: 0.2

[I 2023-04-27 10:29:18,127] Trial 53 finished with value: 0.1221610203385353 and parameters: {'learning_rate': 0.0031007246323629944, 'dropout_rate': 0.03975217012583087, 'num_hidden_layers': 4, 'neurons_per_layer': 235, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 52 with value: 0.11352565735578538.


Epoch 1/100
832/840 [============================>.] - ETA: 0s - loss: 0.3437 - mae: 0.3715 - mse: 0.3437
Epoch: 0, loss:0.3429,  mae:0.3708,  mse:0.3429,  val_loss:0.2417,  val_mae:0.2928,  val_mse:0.2417,  
840/840 [==============================] - 3s 3ms/step - loss: 0.3429 - mae: 0.3708 - mse: 0.3429 - val_loss: 0.2417 - val_mae: 0.2928 - val_mse: 0.2417
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2663 - mae: 0.2994 - mse: 0.2663 - val_loss: 0.2192 - val_mae: 0.2662 - val_mse: 0.2192
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2490 - mae: 0.2833 - mse: 0.2490 - val_loss: 0.2061 - val_mae: 0.2510 - val_mse: 0.2061
Epoch 4/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2382 - mae: 0.2739 - mse: 0.2382 - val_loss: 0.1959 - val_mae: 0.2457 - val_mse: 0.1959
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2264 - mae: 0.2615 - mse: 0.2264 - val_loss: 0.1774 - val_mae: 0.2

[I 2023-04-27 10:30:58,951] Trial 54 finished with value: 0.12558494210243226 and parameters: {'learning_rate': 0.00407419065333212, 'dropout_rate': 0.02974765898933112, 'num_hidden_layers': 5, 'neurons_per_layer': 244, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 52 with value: 0.11352565735578538.


Epoch 1/100
817/840 [============================>.] - ETA: 0s - loss: 0.3243 - mae: 0.3557 - mse: 0.3243
Epoch: 0, loss:0.3236,  mae:0.3554,  mse:0.3236,  val_loss:0.2350,  val_mae:0.2839,  val_mse:0.2350,  
840/840 [==============================] - 2s 2ms/step - loss: 0.3236 - mae: 0.3554 - mse: 0.3236 - val_loss: 0.2350 - val_mae: 0.2839 - val_mse: 0.2350
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2538 - mae: 0.2885 - mse: 0.2538 - val_loss: 0.2129 - val_mae: 0.2681 - val_mse: 0.2129
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2389 - mae: 0.2746 - mse: 0.2389 - val_loss: 0.1911 - val_mae: 0.2342 - val_mse: 0.1911
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2278 - mae: 0.2620 - mse: 0.2278 - val_loss: 0.1765 - val_mae: 0.2235 - val_mse: 0.1765
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2182 - mae: 0.2530 - mse: 0.2182 - val_loss: 0.1668 - val_mae: 0.2

[I 2023-04-27 10:33:25,189] Trial 55 finished with value: 0.11921967044472695 and parameters: {'learning_rate': 0.005420382744543503, 'dropout_rate': 0.02229863295070193, 'num_hidden_layers': 5, 'neurons_per_layer': 223, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 52 with value: 0.11352565735578538.


Epoch 1/100
840/840 [==============================] - ETA: 0s - loss: 0.3787 - mae: 0.4021 - mse: 0.3787
Epoch: 0, loss:0.3787,  mae:0.4021,  mse:0.3787,  val_loss:0.2695,  val_mae:0.3317,  val_mse:0.2695,  
840/840 [==============================] - 2s 2ms/step - loss: 0.3787 - mae: 0.4021 - mse: 0.3787 - val_loss: 0.2695 - val_mae: 0.3317 - val_mse: 0.2695
Epoch 2/100
840/840 [==============================] - 1s 2ms/step - loss: 0.2848 - mae: 0.3264 - mse: 0.2848 - val_loss: 0.2446 - val_mae: 0.2957 - val_mse: 0.2446
Epoch 3/100
840/840 [==============================] - 1s 2ms/step - loss: 0.2730 - mae: 0.3106 - mse: 0.2730 - val_loss: 0.2317 - val_mae: 0.2814 - val_mse: 0.2317
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2632 - mae: 0.2994 - mse: 0.2632 - val_loss: 0.2204 - val_mae: 0.2677 - val_mse: 0.2204
Epoch 5/100
840/840 [==============================] - 1s 2ms/step - loss: 0.2540 - mae: 0.2916 - mse: 0.2540 - val_loss: 0.2136 - val_mae: 0.2

[I 2023-04-27 10:35:46,398] Trial 56 finished with value: 0.1208866335451603 and parameters: {'learning_rate': 0.0022136044914477294, 'dropout_rate': 0.035312736812131026, 'num_hidden_layers': 4, 'neurons_per_layer': 206, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 52 with value: 0.11352565735578538.


Epoch 1/100
805/840 [===========================>..] - ETA: 0s - loss: 0.3407 - mae: 0.3654 - mse: 0.3407
Epoch: 0, loss:0.3388,  mae:0.3645,  mse:0.3388,  val_loss:0.2734,  val_mae:0.3216,  val_mse:0.2734,  
840/840 [==============================] - 1s 1ms/step - loss: 0.3388 - mae: 0.3645 - mse: 0.3388 - val_loss: 0.2734 - val_mae: 0.3216 - val_mse: 0.2734
Epoch 2/100
840/840 [==============================] - 1s 1ms/step - loss: 0.2911 - mae: 0.3310 - mse: 0.2911 - val_loss: 0.2582 - val_mae: 0.3093 - val_mse: 0.2582
Epoch 3/100
840/840 [==============================] - 1s 1ms/step - loss: 0.2826 - mae: 0.3233 - mse: 0.2826 - val_loss: 0.2485 - val_mae: 0.2986 - val_mse: 0.2485
Epoch 4/100
840/840 [==============================] - 1s 1ms/step - loss: 0.2787 - mae: 0.3186 - mse: 0.2787 - val_loss: 0.2428 - val_mae: 0.2956 - val_mse: 0.2428
Epoch 5/100
840/840 [==============================] - 1s 1ms/step - loss: 0.2735 - mae: 0.3131 - mse: 0.2735 - val_loss: 0.2385 - val_mae: 0.2

840/840 [==============================] - 1s 1ms/step - loss: 0.2065 - mae: 0.2567 - mse: 0.2065 - val_loss: 0.1647 - val_mae: 0.2233 - val_mse: 0.1647
Epoch 99/100
840/840 [==============================] - 1s 1ms/step - loss: 0.2092 - mae: 0.2606 - mse: 0.2092 - val_loss: 0.1637 - val_mae: 0.2215 - val_mse: 0.1637
Epoch 100/100
840/840 [==============================] - 1s 1ms/step - loss: 0.2122 - mae: 0.2621 - mse: 0.2122 - val_loss: 0.1680 - val_mae: 0.2228 - val_mse: 0.1680


[I 2023-04-27 10:37:17,680] Trial 57 finished with value: 0.16732380241155625 and parameters: {'learning_rate': 0.002822707051937456, 'dropout_rate': 0.046539368431860094, 'num_hidden_layers': 1, 'neurons_per_layer': 186, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 52 with value: 0.11352565735578538.


Epoch 1/100
830/840 [============================>.] - ETA: 0s - loss: 0.2868 - mae: 0.2884 - mse: 0.2868
Epoch: 0, loss:0.2903,  mae:0.2888,  mse:0.2903,  val_loss:0.1848,  val_mae:0.2188,  val_mse:0.1848,  
840/840 [==============================] - 3s 3ms/step - loss: 0.2903 - mae: 0.2888 - mse: 0.2903 - val_loss: 0.1848 - val_mae: 0.2188 - val_mse: 0.1848
Epoch 2/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2292 - mae: 0.2441 - mse: 0.2292 - val_loss: 0.2047 - val_mae: 0.2130 - val_mse: 0.2047
Epoch 3/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2228 - mae: 0.2396 - mse: 0.2228 - val_loss: 0.1818 - val_mae: 0.2266 - val_mse: 0.1818
Epoch 4/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2126 - mae: 0.2347 - mse: 0.2126 - val_loss: 0.1527 - val_mae: 0.2180 - val_mse: 0.1527
Epoch 5/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2022 - mae: 0.2319 - mse: 0.2022 - val_loss: 0.1861 - val_mae: 0.2

[I 2023-04-27 10:38:16,103] Trial 58 finished with value: 0.14502930343151094 and parameters: {'learning_rate': 0.0018843154211208191, 'dropout_rate': 0.019199296684247507, 'num_hidden_layers': 5, 'neurons_per_layer': 230, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'rms'}. Best is trial 52 with value: 0.11352565735578538.


Epoch 1/100
515/525 [============================>.] - ETA: 0s - loss: 0.4025 - mae: 0.4286 - mse: 0.4025
Epoch: 0, loss:0.4008,  mae:0.4263,  mse:0.4008,  val_loss:0.2610,  val_mae:0.3127,  val_mse:0.2610,  
525/525 [==============================] - 2s 3ms/step - loss: 0.4008 - mae: 0.4263 - mse: 0.4008 - val_loss: 0.2610 - val_mae: 0.3127 - val_mse: 0.2610
Epoch 2/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2724 - mae: 0.3086 - mse: 0.2724 - val_loss: 0.2254 - val_mae: 0.2737 - val_mse: 0.2254
Epoch 3/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2551 - mae: 0.2887 - mse: 0.2551 - val_loss: 0.2145 - val_mae: 0.2573 - val_mse: 0.2145
Epoch 4/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2425 - mae: 0.2772 - mse: 0.2425 - val_loss: 0.1975 - val_mae: 0.2435 - val_mse: 0.1975
Epoch 5/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2343 - mae: 0.2677 - mse: 0.2343 - val_loss: 0.1876 - val_mae: 0.2

[I 2023-04-27 10:40:15,255] Trial 59 finished with value: 0.11328117623925209 and parameters: {'learning_rate': 0.003931416839453604, 'dropout_rate': 0.024815972888615808, 'num_hidden_layers': 6, 'neurons_per_layer': 217, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
514/525 [============================>.] - ETA: 0s - loss: 0.4604 - mae: 0.4697 - mse: 0.4604
Epoch: 0, loss:0.4570,  mae:0.4670,  mse:0.4570,  val_loss:0.2737,  val_mae:0.3322,  val_mse:0.2737,  
525/525 [==============================] - 3s 4ms/step - loss: 0.4570 - mae: 0.4670 - mse: 0.4570 - val_loss: 0.2737 - val_mae: 0.3322 - val_mse: 0.2737
Epoch 2/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2775 - mae: 0.3171 - mse: 0.2775 - val_loss: 0.2263 - val_mae: 0.2798 - val_mse: 0.2263
Epoch 3/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2523 - mae: 0.2924 - mse: 0.2523 - val_loss: 0.2091 - val_mae: 0.2574 - val_mse: 0.2091
Epoch 4/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2424 - mae: 0.2808 - mse: 0.2424 - val_loss: 0.1967 - val_mae: 0.2490 - val_mse: 0.1967
Epoch 5/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2340 - mae: 0.2726 - mse: 0.2340 - val_loss: 0.1882 - val_mae: 0.2

[I 2023-04-27 10:42:41,955] Trial 60 finished with value: 0.12007376477122307 and parameters: {'learning_rate': 0.003940780606331665, 'dropout_rate': 0.023813790801245276, 'num_hidden_layers': 7, 'neurons_per_layer': 215, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
505/525 [===========================>..] - ETA: 0s - loss: 0.3619 - mae: 0.3896 - mse: 0.3619
Epoch: 0, loss:0.3569,  mae:0.3863,  mse:0.3569,  val_loss:0.2447,  val_mae:0.2993,  val_mse:0.2447,  
525/525 [==============================] - 2s 3ms/step - loss: 0.3569 - mae: 0.3863 - mse: 0.3569 - val_loss: 0.2447 - val_mae: 0.2993 - val_mse: 0.2447
Epoch 2/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2670 - mae: 0.3023 - mse: 0.2670 - val_loss: 0.2554 - val_mae: 0.3008 - val_mse: 0.2554
Epoch 3/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2531 - mae: 0.2855 - mse: 0.2531 - val_loss: 0.2119 - val_mae: 0.2591 - val_mse: 0.2119
Epoch 4/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2485 - mae: 0.2801 - mse: 0.2485 - val_loss: 0.1967 - val_mae: 0.2453 - val_mse: 0.1967
Epoch 5/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2328 - mae: 0.2682 - mse: 0.2328 - val_loss: 0.1913 - val_mae: 0.2

[I 2023-04-27 10:44:22,911] Trial 61 finished with value: 0.11430749222636223 and parameters: {'learning_rate': 0.005590009495263449, 'dropout_rate': 0.029049446850913055, 'num_hidden_layers': 6, 'neurons_per_layer': 197, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
520/525 [============================>.] - ETA: 0s - loss: 0.3573 - mae: 0.3833 - mse: 0.3573
Epoch: 0, loss:0.3549,  mae:0.3818,  mse:0.3549,  val_loss:0.2410,  val_mae:0.2945,  val_mse:0.2410,  
525/525 [==============================] - 2s 3ms/step - loss: 0.3549 - mae: 0.3818 - mse: 0.3549 - val_loss: 0.2410 - val_mae: 0.2945 - val_mse: 0.2410
Epoch 2/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2649 - mae: 0.3003 - mse: 0.2649 - val_loss: 0.2172 - val_mae: 0.2678 - val_mse: 0.2172
Epoch 3/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2471 - mae: 0.2811 - mse: 0.2471 - val_loss: 0.1994 - val_mae: 0.2434 - val_mse: 0.1994
Epoch 4/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2395 - mae: 0.2736 - mse: 0.2395 - val_loss: 0.1888 - val_mae: 0.2313 - val_mse: 0.1888
Epoch 5/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2315 - mae: 0.2657 - mse: 0.2315 - val_loss: 0.1801 - val_mae: 0.2

[I 2023-04-27 10:45:32,951] Trial 62 finished with value: 0.12398467138409615 and parameters: {'learning_rate': 0.005861875133844529, 'dropout_rate': 0.028016209161338592, 'num_hidden_layers': 6, 'neurons_per_layer': 239, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
518/525 [============================>.] - ETA: 0s - loss: 0.4294 - mae: 0.4475 - mse: 0.4294
Epoch: 0, loss:0.4280,  mae:0.4461,  mse:0.4280,  val_loss:0.2710,  val_mae:0.3280,  val_mse:0.2710,  
525/525 [==============================] - 2s 3ms/step - loss: 0.4280 - mae: 0.4461 - mse: 0.4280 - val_loss: 0.2710 - val_mae: 0.3280 - val_mse: 0.2710
Epoch 2/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2771 - mae: 0.3192 - mse: 0.2771 - val_loss: 0.2353 - val_mae: 0.2904 - val_mse: 0.2353
Epoch 3/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2597 - mae: 0.2989 - mse: 0.2597 - val_loss: 0.2246 - val_mae: 0.2737 - val_mse: 0.2246
Epoch 4/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2510 - mae: 0.2885 - mse: 0.2510 - val_loss: 0.2127 - val_mae: 0.2641 - val_mse: 0.2127
Epoch 5/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2442 - mae: 0.2805 - mse: 0.2442 - val_loss: 0.2049 - val_mae: 0.2

[I 2023-04-27 10:47:01,401] Trial 63 finished with value: 0.11990825533866882 and parameters: {'learning_rate': 0.002960688057714021, 'dropout_rate': 0.020106230513649584, 'num_hidden_layers': 6, 'neurons_per_layer': 195, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
516/525 [============================>.] - ETA: 0s - loss: 0.3845 - mae: 0.4085 - mse: 0.3845
Epoch: 0, loss:0.3832,  mae:0.4076,  mse:0.3832,  val_loss:0.2574,  val_mae:0.3140,  val_mse:0.2574,  
525/525 [==============================] - 2s 3ms/step - loss: 0.3832 - mae: 0.4076 - mse: 0.3832 - val_loss: 0.2574 - val_mae: 0.3140 - val_mse: 0.2574
Epoch 2/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2735 - mae: 0.3112 - mse: 0.2735 - val_loss: 0.2292 - val_mae: 0.2826 - val_mse: 0.2292
Epoch 3/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2577 - mae: 0.2937 - mse: 0.2577 - val_loss: 0.2126 - val_mae: 0.2603 - val_mse: 0.2126
Epoch 4/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2507 - mae: 0.2857 - mse: 0.2507 - val_loss: 0.2038 - val_mae: 0.2492 - val_mse: 0.2038
Epoch 5/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2407 - mae: 0.2753 - mse: 0.2407 - val_loss: 0.1922 - val_mae: 0.2

[I 2023-04-27 10:48:42,843] Trial 64 finished with value: 0.1210972674190998 and parameters: {'learning_rate': 0.004690995607256259, 'dropout_rate': 0.031943077604467005, 'num_hidden_layers': 6, 'neurons_per_layer': 228, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
505/525 [===========================>..] - ETA: 0s - loss: 0.4270 - mae: 0.4467 - mse: 0.4270
Epoch: 0, loss:0.4205,  mae:0.4413,  mse:0.4205,  val_loss:0.2527,  val_mae:0.3092,  val_mse:0.2527,  
525/525 [==============================] - 2s 3ms/step - loss: 0.4205 - mae: 0.4413 - mse: 0.4205 - val_loss: 0.2527 - val_mae: 0.3092 - val_mse: 0.2527
Epoch 2/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2727 - mae: 0.3061 - mse: 0.2727 - val_loss: 0.2237 - val_mae: 0.2736 - val_mse: 0.2237
Epoch 3/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2575 - mae: 0.2907 - mse: 0.2575 - val_loss: 0.2229 - val_mae: 0.2658 - val_mse: 0.2229
Epoch 4/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2512 - mae: 0.2822 - mse: 0.2512 - val_loss: 0.2030 - val_mae: 0.2522 - val_mse: 0.2030
Epoch 5/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2396 - mae: 0.2737 - mse: 0.2396 - val_loss: 0.1941 - val_mae: 0.2

[I 2023-04-27 10:50:21,170] Trial 65 finished with value: 0.1177458941936493 and parameters: {'learning_rate': 0.003591168182574805, 'dropout_rate': 0.02499109531329539, 'num_hidden_layers': 7, 'neurons_per_layer': 177, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
507/525 [===========================>..] - ETA: 0s - loss: 0.4430 - mae: 0.4541 - mse: 0.4430
Epoch: 0, loss:0.4368,  mae:0.4499,  mse:0.4368,  val_loss:0.2852,  val_mae:0.3523,  val_mse:0.2852,  
525/525 [==============================] - 2s 3ms/step - loss: 0.4368 - mae: 0.4499 - mse: 0.4368 - val_loss: 0.2852 - val_mae: 0.3523 - val_mse: 0.2852
Epoch 2/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2841 - mae: 0.3332 - mse: 0.2841 - val_loss: 0.2468 - val_mae: 0.3045 - val_mse: 0.2468
Epoch 3/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2643 - mae: 0.3061 - mse: 0.2643 - val_loss: 0.2318 - val_mae: 0.2815 - val_mse: 0.2318
Epoch 4/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2527 - mae: 0.2929 - mse: 0.2527 - val_loss: 0.2240 - val_mae: 0.2714 - val_mse: 0.2240
Epoch 5/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2465 - mae: 0.2826 - mse: 0.2465 - val_loss: 0.2139 - val_mae: 0.2

[I 2023-04-27 10:51:53,854] Trial 66 finished with value: 0.12484095916152001 and parameters: {'learning_rate': 0.002281832656476369, 'dropout_rate': 0.01329690133797366, 'num_hidden_layers': 5, 'neurons_per_layer': 208, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
498/525 [===========================>..] - ETA: 0s - loss: 0.3108 - mae: 0.3472 - mse: 0.3108
Epoch: 0, loss:0.3077,  mae:0.3450,  mse:0.3077,  val_loss:0.2479,  val_mae:0.3035,  val_mse:0.2479,  
525/525 [==============================] - 1s 2ms/step - loss: 0.3077 - mae: 0.3450 - mse: 0.3077 - val_loss: 0.2479 - val_mae: 0.3035 - val_mse: 0.2479
Epoch 2/100
525/525 [==============================] - 1s 1ms/step - loss: 0.2654 - mae: 0.3036 - mse: 0.2654 - val_loss: 0.2326 - val_mae: 0.2874 - val_mse: 0.2326
Epoch 3/100
525/525 [==============================] - 1s 1ms/step - loss: 0.2546 - mae: 0.2939 - mse: 0.2546 - val_loss: 0.2234 - val_mae: 0.2744 - val_mse: 0.2234
Epoch 4/100
525/525 [==============================] - 1s 1ms/step - loss: 0.2475 - mae: 0.2858 - mse: 0.2475 - val_loss: 0.2144 - val_mae: 0.2658 - val_mse: 0.2144
Epoch 5/100
525/525 [==============================] - 1s 1ms/step - loss: 0.2405 - mae: 0.2791 - mse: 0.2405 - val_loss: 0.2072 - val_mae: 0.2

[I 2023-04-27 10:53:10,868] Trial 67 finished with value: 0.1310487747192383 and parameters: {'learning_rate': 0.0063741692772856275, 'dropout_rate': 0.017353769113442937, 'num_hidden_layers': 2, 'neurons_per_layer': 254, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
829/840 [============================>.] - ETA: 0s - loss: 0.4269 - mae: 0.4233 - mse: 0.4269
Epoch: 0, loss:0.4256,  mae:0.4226,  mse:0.4256,  val_loss:0.3158,  val_mae:0.3620,  val_mse:0.3158,  
840/840 [==============================] - 2s 2ms/step - loss: 0.4256 - mae: 0.4226 - mse: 0.4256 - val_loss: 0.3158 - val_mae: 0.3620 - val_mse: 0.3158
Epoch 2/100
840/840 [==============================] - 1s 1ms/step - loss: 0.3776 - mae: 0.3915 - mse: 0.3776 - val_loss: 0.2665 - val_mae: 0.3296 - val_mse: 0.2665
Epoch 3/100
840/840 [==============================] - 1s 1ms/step - loss: 0.3711 - mae: 0.3847 - mse: 0.3711 - val_loss: 0.2542 - val_mae: 0.3154 - val_mse: 0.2542
Epoch 4/100
840/840 [==============================] - 1s 1ms/step - loss: 0.3676 - mae: 0.3793 - mse: 0.3676 - val_loss: 0.2474 - val_mae: 0.2954 - val_mse: 0.2474
Epoch 5/100
840/840 [==============================] - 1s 1ms/step - loss: 0.3661 - mae: 0.3754 - mse: 0.3661 - val_loss: 0.2838 - val_mae: 0.3

[I 2023-04-27 10:53:33,019] Trial 68 finished with value: 0.24049084335565568 and parameters: {'learning_rate': 0.004932633426160063, 'dropout_rate': 0.0396583012776479, 'num_hidden_layers': 6, 'neurons_per_layer': 2, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'adam'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
417/420 [============================>.] - ETA: 0s - loss: 0.3820 - mae: 0.4016 - mse: 0.3820
Epoch: 0, loss:0.3809,  mae:0.4011,  mse:0.3809,  val_loss:0.2378,  val_mae:0.2884,  val_mse:0.2378,  
420/420 [==============================] - 2s 3ms/step - loss: 0.3809 - mae: 0.4011 - mse: 0.3809 - val_loss: 0.2378 - val_mae: 0.2884 - val_mse: 0.2378
Epoch 2/100
420/420 [==============================] - 2s 4ms/step - loss: 0.2610 - mae: 0.2970 - mse: 0.2610 - val_loss: 0.2145 - val_mae: 0.2612 - val_mse: 0.2145
Epoch 3/100
420/420 [==============================] - 2s 4ms/step - loss: 0.2484 - mae: 0.2831 - mse: 0.2484 - val_loss: 0.2011 - val_mae: 0.2529 - val_mse: 0.2011
Epoch 4/100
420/420 [==============================] - 2s 4ms/step - loss: 0.2384 - mae: 0.2729 - mse: 0.2384 - val_loss: 0.1916 - val_mae: 0.2454 - val_mse: 0.1916
Epoch 5/100
420/420 [==============================] - 2s 4ms/step - loss: 0.2274 - mae: 0.2640 - mse: 0.2274 - val_loss: 0.1776 - val_mae: 0.2

[I 2023-04-27 10:54:49,312] Trial 69 finished with value: 0.12155144587159157 and parameters: {'learning_rate': 0.008561401253327177, 'dropout_rate': 0.022668053780719597, 'num_hidden_layers': 6, 'neurons_per_layer': 164, 'batch_size': 20, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
825/840 [============================>.] - ETA: 0s - loss: 0.4755 - mae: 0.4907 - mse: 0.4755
Epoch: 0, loss:0.4714,  mae:0.4875,  mse:0.4714,  val_loss:0.2865,  val_mae:0.3443,  val_mse:0.2865,  
840/840 [==============================] - 3s 3ms/step - loss: 0.4714 - mae: 0.4875 - mse: 0.4714 - val_loss: 0.2865 - val_mae: 0.3443 - val_mse: 0.2865
Epoch 2/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2902 - mae: 0.3256 - mse: 0.2902 - val_loss: 0.2475 - val_mae: 0.2959 - val_mse: 0.2475
Epoch 3/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2689 - mae: 0.3025 - mse: 0.2689 - val_loss: 0.2303 - val_mae: 0.2785 - val_mse: 0.2303
Epoch 4/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2591 - mae: 0.2922 - mse: 0.2591 - val_loss: 0.2181 - val_mae: 0.2648 - val_mse: 0.2181
Epoch 5/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2508 - mae: 0.2827 - mse: 0.2508 - val_loss: 0.2078 - val_mae: 0.2

[I 2023-04-27 10:58:06,692] Trial 70 finished with value: 0.12258028835058213 and parameters: {'learning_rate': 0.0016149426895373856, 'dropout_rate': 0.026816357539575682, 'num_hidden_layers': 7, 'neurons_per_layer': 221, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
267/280 [===========================>..] - ETA: 0s - loss: 0.4482 - mae: 0.4583 - mse: 0.4482
Epoch: 0, loss:0.4411,  mae:0.4543,  mse:0.4411,  val_loss:0.2860,  val_mae:0.3482,  val_mse:0.2860,  
280/280 [==============================] - 1s 3ms/step - loss: 0.4411 - mae: 0.4543 - mse: 0.4411 - val_loss: 0.2860 - val_mae: 0.3482 - val_mse: 0.2860
Epoch 2/100
280/280 [==============================] - 1s 2ms/step - loss: 0.3033 - mae: 0.3485 - mse: 0.3033 - val_loss: 0.2567 - val_mae: 0.3171 - val_mse: 0.2567
Epoch 3/100
280/280 [==============================] - 1s 2ms/step - loss: 0.2815 - mae: 0.3254 - mse: 0.2815 - val_loss: 0.2405 - val_mae: 0.2946 - val_mse: 0.2405
Epoch 4/100
280/280 [==============================] - 1s 2ms/step - loss: 0.2754 - mae: 0.3157 - mse: 0.2754 - val_loss: 0.2361 - val_mae: 0.2849 - val_mse: 0.2361
Epoch 5/100
280/280 [==============================] - 1s 2ms/step - loss: 0.2712 - mae: 0.3086 - mse: 0.2712 - val_loss: 0.2259 - val_mae: 0.2

280/280 [==============================] - 1s 3ms/step - loss: 0.1736 - mae: 0.2085 - mse: 0.1736 - val_loss: 0.1263 - val_mae: 0.1629 - val_mse: 0.1263
Epoch 99/100
280/280 [==============================] - 1s 3ms/step - loss: 0.1721 - mae: 0.2063 - mse: 0.1721 - val_loss: 0.1280 - val_mae: 0.1616 - val_mse: 0.1280
Epoch 100/100
280/280 [==============================] - 1s 3ms/step - loss: 0.1691 - mae: 0.2049 - mse: 0.1691 - val_loss: 0.1306 - val_mae: 0.1647 - val_mse: 0.1306


[I 2023-04-27 10:59:24,466] Trial 71 finished with value: 0.12711505219340324 and parameters: {'learning_rate': 0.004459045118833166, 'dropout_rate': 0.051572346030079104, 'num_hidden_layers': 5, 'neurons_per_layer': 202, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
262/280 [===========================>..] - ETA: 0s - loss: 0.3963 - mae: 0.4179 - mse: 0.3963
Epoch: 0, loss:0.3881,  mae:0.4124,  mse:0.3881,  val_loss:0.2719,  val_mae:0.3244,  val_mse:0.2719,  
280/280 [==============================] - 1s 3ms/step - loss: 0.3881 - mae: 0.4124 - mse: 0.3881 - val_loss: 0.2719 - val_mae: 0.3244 - val_mse: 0.2719
Epoch 2/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2870 - mae: 0.3233 - mse: 0.2870 - val_loss: 0.2459 - val_mae: 0.2952 - val_mse: 0.2459
Epoch 3/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2745 - mae: 0.3085 - mse: 0.2745 - val_loss: 0.2323 - val_mae: 0.2785 - val_mse: 0.2323
Epoch 4/100
280/280 [==============================] - 1s 2ms/step - loss: 0.2651 - mae: 0.2983 - mse: 0.2651 - val_loss: 0.2228 - val_mae: 0.2701 - val_mse: 0.2228
Epoch 5/100
280/280 [==============================] - 1s 2ms/step - loss: 0.2572 - mae: 0.2929 - mse: 0.2572 - val_loss: 0.2133 - val_mae: 0.2

280/280 [==============================] - 1s 2ms/step - loss: 0.1581 - mae: 0.1919 - mse: 0.1581 - val_loss: 0.1157 - val_mae: 0.1530 - val_mse: 0.1157
Epoch 99/100
280/280 [==============================] - 1s 3ms/step - loss: 0.1565 - mae: 0.1897 - mse: 0.1565 - val_loss: 0.1149 - val_mae: 0.1534 - val_mse: 0.1149
Epoch 100/100
280/280 [==============================] - 1s 3ms/step - loss: 0.1545 - mae: 0.1901 - mse: 0.1545 - val_loss: 0.1167 - val_mae: 0.1546 - val_mse: 0.1167


[I 2023-04-27 11:00:37,716] Trial 72 finished with value: 0.11791049316525459 and parameters: {'learning_rate': 0.006395138350152488, 'dropout_rate': 0.03458851403409859, 'num_hidden_layers': 5, 'neurons_per_layer': 183, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
512/525 [============================>.] - ETA: 0s - loss: 0.3988 - mae: 0.4245 - mse: 0.3988
Epoch: 0, loss:0.3953,  mae:0.4218,  mse:0.3953,  val_loss:0.2688,  val_mae:0.3286,  val_mse:0.2688,  
525/525 [==============================] - 2s 3ms/step - loss: 0.3953 - mae: 0.4218 - mse: 0.3953 - val_loss: 0.2688 - val_mae: 0.3286 - val_mse: 0.2688
Epoch 2/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2818 - mae: 0.3214 - mse: 0.2818 - val_loss: 0.2340 - val_mae: 0.2872 - val_mse: 0.2340
Epoch 3/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2631 - mae: 0.3007 - mse: 0.2631 - val_loss: 0.2181 - val_mae: 0.2696 - val_mse: 0.2181
Epoch 4/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2521 - mae: 0.2894 - mse: 0.2521 - val_loss: 0.2060 - val_mae: 0.2545 - val_mse: 0.2060
Epoch 5/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2449 - mae: 0.2809 - mse: 0.2449 - val_loss: 0.1993 - val_mae: 0.2

[I 2023-04-27 11:02:29,440] Trial 73 finished with value: 0.12147075533866883 and parameters: {'learning_rate': 0.0034031430583851465, 'dropout_rate': 0.031412138279157245, 'num_hidden_layers': 6, 'neurons_per_layer': 240, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
271/280 [============================>.] - ETA: 0s - loss: 0.4116 - mae: 0.4200 - mse: 0.4116
Epoch: 0, loss:0.4093,  mae:0.4178,  mse:0.4093,  val_loss:0.2893,  val_mae:0.3435,  val_mse:0.2893,  
280/280 [==============================] - 2s 3ms/step - loss: 0.4093 - mae: 0.4178 - mse: 0.4093 - val_loss: 0.2893 - val_mae: 0.3435 - val_mse: 0.2893
Epoch 2/100
280/280 [==============================] - 0s 2ms/step - loss: 0.2948 - mae: 0.3353 - mse: 0.2948 - val_loss: 0.2469 - val_mae: 0.3010 - val_mse: 0.2469
Epoch 3/100
280/280 [==============================] - 1s 2ms/step - loss: 0.2743 - mae: 0.3113 - mse: 0.2743 - val_loss: 0.2292 - val_mae: 0.2742 - val_mse: 0.2292
Epoch 4/100
280/280 [==============================] - 1s 2ms/step - loss: 0.2607 - mae: 0.2952 - mse: 0.2607 - val_loss: 0.2224 - val_mae: 0.2721 - val_mse: 0.2224
Epoch 5/100
280/280 [==============================] - 0s 1ms/step - loss: 0.2594 - mae: 0.2944 - mse: 0.2594 - val_loss: 0.2179 - val_mae: 0.2

280/280 [==============================] - 0s 1ms/step - loss: 0.1592 - mae: 0.1947 - mse: 0.1592 - val_loss: 0.1172 - val_mae: 0.1540 - val_mse: 0.1172
Epoch 99/100
280/280 [==============================] - 0s 2ms/step - loss: 0.1563 - mae: 0.1896 - mse: 0.1563 - val_loss: 0.1203 - val_mae: 0.1578 - val_mse: 0.1203
Epoch 100/100
280/280 [==============================] - 0s 2ms/step - loss: 0.1599 - mae: 0.1927 - mse: 0.1599 - val_loss: 0.1238 - val_mae: 0.1571 - val_mse: 0.1238


[I 2023-04-27 11:03:15,364] Trial 74 finished with value: 0.1215759538114071 and parameters: {'learning_rate': 0.01011334475929039, 'dropout_rate': 0.020561282915643585, 'num_hidden_layers': 5, 'neurons_per_layer': 37, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
832/840 [============================>.] - ETA: 0s - loss: 0.3645 - mae: 0.3236 - mse: 0.3645
Epoch: 0, loss:0.3640,  mae:0.3235,  mse:0.3640,  val_loss:0.3278,  val_mae:0.2911,  val_mse:0.3278,  
840/840 [==============================] - 3s 3ms/step - loss: 0.3640 - mae: 0.3235 - mse: 0.3640 - val_loss: 0.3278 - val_mae: 0.2911 - val_mse: 0.3278
Epoch 2/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2646 - mae: 0.2905 - mse: 0.2646 - val_loss: 0.2197 - val_mae: 0.2655 - val_mse: 0.2197
Epoch 3/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2590 - mae: 0.2959 - mse: 0.2590 - val_loss: 0.1879 - val_mae: 0.2469 - val_mse: 0.1879
Epoch 4/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2489 - mae: 0.2858 - mse: 0.2489 - val_loss: 0.1637 - val_mae: 0.2132 - val_mse: 0.1637
Epoch 5/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2328 - mae: 0.2699 - mse: 0.2328 - val_loss: 0.2143 - val_mae: 0.2

[I 2023-04-27 11:04:09,731] Trial 75 finished with value: 0.1647803232073784 and parameters: {'learning_rate': 0.005347939054345487, 'dropout_rate': 0.038072142741638074, 'num_hidden_layers': 5, 'neurons_per_layer': 195, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'rms'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
505/525 [===========================>..] - ETA: 0s - loss: 0.3635 - mae: 0.3920 - mse: 0.3635
Epoch: 0, loss:0.3600,  mae:0.3894,  mse:0.3600,  val_loss:0.2475,  val_mae:0.3001,  val_mse:0.2475,  
525/525 [==============================] - 2s 3ms/step - loss: 0.3600 - mae: 0.3894 - mse: 0.3600 - val_loss: 0.2475 - val_mae: 0.3001 - val_mse: 0.2475
Epoch 2/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2751 - mae: 0.3074 - mse: 0.2751 - val_loss: 0.2256 - val_mae: 0.2747 - val_mse: 0.2256
Epoch 3/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2627 - mae: 0.2950 - mse: 0.2627 - val_loss: 0.2180 - val_mae: 0.2627 - val_mse: 0.2180
Epoch 4/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2555 - mae: 0.2882 - mse: 0.2555 - val_loss: 0.2029 - val_mae: 0.2515 - val_mse: 0.2029
Epoch 5/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2460 - mae: 0.2800 - mse: 0.2460 - val_loss: 0.1962 - val_mae: 0.2

[I 2023-04-27 11:06:15,159] Trial 76 finished with value: 0.11950224488973618 and parameters: {'learning_rate': 0.0043237361453279145, 'dropout_rate': 0.045414353548284284, 'num_hidden_layers': 6, 'neurons_per_layer': 215, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
833/840 [============================>.] - ETA: 0s - loss: 0.3495 - mae: 0.3799 - mse: 0.3495
Epoch: 0, loss:0.3501,  mae:0.3804,  mse:0.3501,  val_loss:0.2624,  val_mae:0.3167,  val_mse:0.2624,  
840/840 [==============================] - 4s 4ms/step - loss: 0.3501 - mae: 0.3804 - mse: 0.3501 - val_loss: 0.2624 - val_mae: 0.3167 - val_mse: 0.2624
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2737 - mae: 0.3107 - mse: 0.2737 - val_loss: 0.2384 - val_mae: 0.2849 - val_mse: 0.2384
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2597 - mae: 0.2944 - mse: 0.2597 - val_loss: 0.2275 - val_mae: 0.2738 - val_mse: 0.2275
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2511 - mae: 0.2861 - mse: 0.2511 - val_loss: 0.2126 - val_mae: 0.2600 - val_mse: 0.2126
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2459 - mae: 0.2801 - mse: 0.2459 - val_loss: 0.2064 - val_mae: 0.2

[I 2023-04-27 11:08:39,396] Trial 77 finished with value: 0.12163852006196976 and parameters: {'learning_rate': 0.0027416762978584018, 'dropout_rate': 0.026031748793017916, 'num_hidden_layers': 4, 'neurons_per_layer': 227, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
270/280 [===========================>..] - ETA: 0s - loss: 0.5404 - mae: 0.5227 - mse: 0.5404
Epoch: 0, loss:0.5353,  mae:0.5199,  mse:0.5353,  val_loss:0.3300,  val_mae:0.4205,  val_mse:0.3300,  
280/280 [==============================] - 2s 4ms/step - loss: 0.5353 - mae: 0.5199 - mse: 0.5353 - val_loss: 0.3300 - val_mae: 0.4205 - val_mse: 0.3300
Epoch 2/100
280/280 [==============================] - 1s 3ms/step - loss: 0.3198 - mae: 0.3683 - mse: 0.3198 - val_loss: 0.2812 - val_mae: 0.3369 - val_mse: 0.2812
Epoch 3/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2966 - mae: 0.3379 - mse: 0.2966 - val_loss: 0.2583 - val_mae: 0.3143 - val_mse: 0.2583
Epoch 4/100
280/280 [==============================] - 1s 3ms/step - loss: 0.2785 - mae: 0.3214 - mse: 0.2785 - val_loss: 0.2414 - val_mae: 0.2944 - val_mse: 0.2414
Epoch 5/100
280/280 [==============================] - 1s 4ms/step - loss: 0.2691 - mae: 0.3094 - mse: 0.2691 - val_loss: 0.2319 - val_mae: 0.2

280/280 [==============================] - 1s 3ms/step - loss: 0.1663 - mae: 0.2026 - mse: 0.1663 - val_loss: 0.1321 - val_mae: 0.1662 - val_mse: 0.1321
Epoch 99/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1685 - mae: 0.2023 - mse: 0.1685 - val_loss: 0.1280 - val_mae: 0.1677 - val_mse: 0.1280
Epoch 100/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1643 - mae: 0.2008 - mse: 0.1643 - val_loss: 0.1275 - val_mae: 0.1696 - val_mse: 0.1275


[I 2023-04-27 11:10:02,990] Trial 78 finished with value: 0.12850499153137207 and parameters: {'learning_rate': 0.0035071514410444414, 'dropout_rate': 0.031896852991414225, 'num_hidden_layers': 5, 'neurons_per_layer': 204, 'batch_size': 30, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
412/420 [============================>.] - ETA: 0s - loss: 0.3683 - mae: 0.3974 - mse: 0.3683
Epoch: 0, loss:0.3654,  mae:0.3952,  mse:0.3654,  val_loss:0.2513,  val_mae:0.3011,  val_mse:0.2513,  
420/420 [==============================] - 3s 5ms/step - loss: 0.3654 - mae: 0.3952 - mse: 0.3654 - val_loss: 0.2513 - val_mae: 0.3011 - val_mse: 0.2513
Epoch 2/100
420/420 [==============================] - 2s 4ms/step - loss: 0.2702 - mae: 0.3031 - mse: 0.2702 - val_loss: 0.2253 - val_mae: 0.2719 - val_mse: 0.2253
Epoch 3/100
420/420 [==============================] - 2s 4ms/step - loss: 0.2559 - mae: 0.2875 - mse: 0.2559 - val_loss: 0.2106 - val_mae: 0.2596 - val_mse: 0.2106
Epoch 4/100
420/420 [==============================] - 2s 4ms/step - loss: 0.2443 - mae: 0.2778 - mse: 0.2443 - val_loss: 0.1944 - val_mae: 0.2374 - val_mse: 0.1944
Epoch 5/100
420/420 [==============================] - 2s 4ms/step - loss: 0.2331 - mae: 0.2650 - mse: 0.2331 - val_loss: 0.1865 - val_mae: 0.2

[I 2023-04-27 11:11:51,198] Trial 79 finished with value: 0.11998665407299995 and parameters: {'learning_rate': 0.007243399260580232, 'dropout_rate': 0.028308196623752894, 'num_hidden_layers': 6, 'neurons_per_layer': 277, 'batch_size': 20, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
514/525 [============================>.] - ETA: 0s - loss: 0.3190 - mae: 0.3322 - mse: 0.3190
Epoch: 0, loss:0.3174,  mae:0.3309,  mse:0.3174,  val_loss:0.2612,  val_mae:0.2722,  val_mse:0.2612,  
525/525 [==============================] - 2s 3ms/step - loss: 0.3174 - mae: 0.3309 - mse: 0.3174 - val_loss: 0.2612 - val_mae: 0.2722 - val_mse: 0.2612
Epoch 2/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2815 - mae: 0.3139 - mse: 0.2815 - val_loss: 0.2077 - val_mae: 0.2753 - val_mse: 0.2077
Epoch 3/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2683 - mae: 0.2931 - mse: 0.2683 - val_loss: 0.2375 - val_mae: 0.2889 - val_mse: 0.2375
Epoch 4/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2825 - mae: 0.3003 - mse: 0.2825 - val_loss: 0.3964 - val_mae: 0.3905 - val_mse: 0.3964
Epoch 5/100
525/525 [==============================] - 1s 3ms/step - loss: 0.3062 - mae: 0.3061 - mse: 0.3062 - val_loss: 0.2372 - val_mae: 0.2

[I 2023-04-27 11:12:20,185] Trial 80 finished with value: 0.2226810187101364 and parameters: {'learning_rate': 0.009106592910426241, 'dropout_rate': 0.03779524703703007, 'num_hidden_layers': 5, 'neurons_per_layer': 176, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'adam'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
515/525 [============================>.] - ETA: 0s - loss: 0.4819 - mae: 0.4937 - mse: 0.4819
Epoch: 0, loss:0.4780,  mae:0.4907,  mse:0.4780,  val_loss:0.2823,  val_mae:0.3354,  val_mse:0.2823,  
525/525 [==============================] - 2s 3ms/step - loss: 0.4780 - mae: 0.4907 - mse: 0.4780 - val_loss: 0.2823 - val_mae: 0.3354 - val_mse: 0.2823
Epoch 2/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2845 - mae: 0.3214 - mse: 0.2845 - val_loss: 0.2367 - val_mae: 0.2903 - val_mse: 0.2367
Epoch 3/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2659 - mae: 0.3018 - mse: 0.2659 - val_loss: 0.2265 - val_mae: 0.2773 - val_mse: 0.2265
Epoch 4/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2508 - mae: 0.2879 - mse: 0.2508 - val_loss: 0.2068 - val_mae: 0.2539 - val_mse: 0.2068
Epoch 5/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2429 - mae: 0.2776 - mse: 0.2429 - val_loss: 0.1989 - val_mae: 0.2

[I 2023-04-27 11:14:15,794] Trial 81 finished with value: 0.11402601599693299 and parameters: {'learning_rate': 0.003461307693227179, 'dropout_rate': 0.024029637563773947, 'num_hidden_layers': 7, 'neurons_per_layer': 173, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
520/525 [============================>.] - ETA: 0s - loss: 0.3740 - mae: 0.3974 - mse: 0.3740
Epoch: 0, loss:0.3727,  mae:0.3963,  mse:0.3727,  val_loss:0.2421,  val_mae:0.2937,  val_mse:0.2421,  
525/525 [==============================] - 2s 3ms/step - loss: 0.3727 - mae: 0.3963 - mse: 0.3727 - val_loss: 0.2421 - val_mae: 0.2937 - val_mse: 0.2421
Epoch 2/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2647 - mae: 0.2986 - mse: 0.2647 - val_loss: 0.2169 - val_mae: 0.2686 - val_mse: 0.2169
Epoch 3/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2517 - mae: 0.2846 - mse: 0.2517 - val_loss: 0.2067 - val_mae: 0.2518 - val_mse: 0.2067
Epoch 4/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2374 - mae: 0.2726 - mse: 0.2374 - val_loss: 0.1916 - val_mae: 0.2389 - val_mse: 0.1916
Epoch 5/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2284 - mae: 0.2634 - mse: 0.2284 - val_loss: 0.1831 - val_mae: 0.2

[I 2023-04-27 11:15:26,968] Trial 82 finished with value: 0.12228738665580749 and parameters: {'learning_rate': 0.005110415466040675, 'dropout_rate': 0.02393819234653107, 'num_hidden_layers': 7, 'neurons_per_layer': 155, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
525/525 [==============================] - ETA: 0s - loss: 0.4531 - mae: 0.4733 - mse: 0.4531
Epoch: 0, loss:0.4531,  mae:0.4733,  mse:0.4531,  val_loss:0.2760,  val_mae:0.3258,  val_mse:0.2760,  
525/525 [==============================] - 2s 4ms/step - loss: 0.4531 - mae: 0.4733 - mse: 0.4531 - val_loss: 0.2760 - val_mae: 0.3258 - val_mse: 0.2760
Epoch 2/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2834 - mae: 0.3131 - mse: 0.2834 - val_loss: 0.2428 - val_mae: 0.2914 - val_mse: 0.2428
Epoch 3/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2665 - mae: 0.2973 - mse: 0.2665 - val_loss: 0.2299 - val_mae: 0.2717 - val_mse: 0.2299
Epoch 4/100
525/525 [==============================] - 2s 3ms/step - loss: 0.2539 - mae: 0.2855 - mse: 0.2539 - val_loss: 0.2189 - val_mae: 0.2700 - val_mse: 0.2189
Epoch 5/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2467 - mae: 0.2815 - mse: 0.2467 - val_loss: 0.2075 - val_mae: 0.2

[I 2023-04-27 11:17:08,487] Trial 83 finished with value: 0.1226368635892868 and parameters: {'learning_rate': 0.0032464826131103335, 'dropout_rate': 0.021060528637235582, 'num_hidden_layers': 7, 'neurons_per_layer': 193, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
523/525 [============================>.] - ETA: 0s - loss: 0.4338 - mae: 0.4472 - mse: 0.4338
Epoch: 0, loss:0.4330,  mae:0.4467,  mse:0.4330,  val_loss:0.2598,  val_mae:0.3269,  val_mse:0.2598,  
525/525 [==============================] - 2s 3ms/step - loss: 0.4330 - mae: 0.4467 - mse: 0.4330 - val_loss: 0.2598 - val_mae: 0.3269 - val_mse: 0.2598
Epoch 2/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2696 - mae: 0.3145 - mse: 0.2696 - val_loss: 0.2241 - val_mae: 0.2825 - val_mse: 0.2241
Epoch 3/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2496 - mae: 0.2904 - mse: 0.2496 - val_loss: 0.2111 - val_mae: 0.2603 - val_mse: 0.2111
Epoch 4/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2393 - mae: 0.2764 - mse: 0.2393 - val_loss: 0.1966 - val_mae: 0.2493 - val_mse: 0.1966
Epoch 5/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2301 - mae: 0.2684 - mse: 0.2301 - val_loss: 0.1921 - val_mae: 0.2

[I 2023-04-27 11:18:16,456] Trial 84 finished with value: 0.12749917060136795 and parameters: {'learning_rate': 0.004132862495096342, 'dropout_rate': 0.01769782160681566, 'num_hidden_layers': 6, 'neurons_per_layer': 168, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1049/1050 [============================>.] - ETA: 0s - loss: 0.4203 - mae: 0.4425 - mse: 0.4203
Epoch: 0, loss:0.4202,  mae:0.4423,  mse:0.4202,  val_loss:0.2605,  val_mae:0.3105,  val_mse:0.2605,  
1050/1050 [==============================] - 3s 3ms/step - loss: 0.4202 - mae: 0.4423 - mse: 0.4202 - val_loss: 0.2605 - val_mae: 0.3105 - val_mse: 0.2605
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2772 - mae: 0.3101 - mse: 0.2772 - val_loss: 0.2262 - val_mae: 0.2713 - val_mse: 0.2262
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2671 - mae: 0.2965 - mse: 0.2671 - val_loss: 0.2143 - val_mae: 0.2589 - val_mse: 0.2143
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2519 - mae: 0.2833 - mse: 0.2519 - val_loss: 0.2039 - val_mae: 0.2505 - val_mse: 0.2039
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2420 - mae: 0.2757 - mse: 0.2420 - val_loss: 0.1963 - 

[I 2023-04-27 11:21:58,888] Trial 85 finished with value: 0.11861055195331574 and parameters: {'learning_rate': 0.002061465199327459, 'dropout_rate': 0.03411501098507363, 'num_hidden_layers': 7, 'neurons_per_layer': 188, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
818/840 [============================>.] - ETA: 0s - loss: 0.3651 - mae: 0.3988 - mse: 0.3651
Epoch: 0, loss:0.3633,  mae:0.3969,  mse:0.3633,  val_loss:0.2613,  val_mae:0.3169,  val_mse:0.2613,  
840/840 [==============================] - 3s 2ms/step - loss: 0.3633 - mae: 0.3969 - mse: 0.3633 - val_loss: 0.2613 - val_mae: 0.3169 - val_mse: 0.2613
Epoch 2/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2793 - mae: 0.3166 - mse: 0.2793 - val_loss: 0.2367 - val_mae: 0.2851 - val_mse: 0.2367
Epoch 3/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2667 - mae: 0.3005 - mse: 0.2667 - val_loss: 0.2245 - val_mae: 0.2726 - val_mse: 0.2245
Epoch 4/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2572 - mae: 0.2919 - mse: 0.2572 - val_loss: 0.2181 - val_mae: 0.2652 - val_mse: 0.2181
Epoch 5/100
840/840 [==============================] - 2s 2ms/step - loss: 0.2449 - mae: 0.2811 - mse: 0.2449 - val_loss: 0.2033 - val_mae: 0.2

[I 2023-04-27 11:24:38,408] Trial 86 finished with value: 0.12204461693763732 and parameters: {'learning_rate': 0.002497314875250912, 'dropout_rate': 0.028479829384392825, 'num_hidden_layers': 5, 'neurons_per_layer': 216, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
503/525 [===========================>..] - ETA: 0s - loss: 0.3728 - mae: 0.3974 - mse: 0.3728
Epoch: 0, loss:0.3663,  mae:0.3932,  mse:0.3663,  val_loss:0.2687,  val_mae:0.3284,  val_mse:0.2687,  
525/525 [==============================] - 2s 2ms/step - loss: 0.3663 - mae: 0.3932 - mse: 0.3663 - val_loss: 0.2687 - val_mae: 0.3284 - val_mse: 0.2687
Epoch 2/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2870 - mae: 0.3261 - mse: 0.2870 - val_loss: 0.2466 - val_mae: 0.3013 - val_mse: 0.2466
Epoch 3/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2772 - mae: 0.3149 - mse: 0.2772 - val_loss: 0.2360 - val_mae: 0.2888 - val_mse: 0.2360
Epoch 4/100
525/525 [==============================] - 1s 2ms/step - loss: 0.2714 - mae: 0.3077 - mse: 0.2714 - val_loss: 0.2276 - val_mae: 0.2791 - val_mse: 0.2276
Epoch 5/100
525/525 [==============================] - 1s 3ms/step - loss: 0.2656 - mae: 0.3026 - mse: 0.2656 - val_loss: 0.2219 - val_mae: 0.2

525/525 [==============================] - 1s 2ms/step - loss: 0.1671 - mae: 0.2036 - mse: 0.1671 - val_loss: 0.1240 - val_mae: 0.1642 - val_mse: 0.1240
Epoch 99/100
525/525 [==============================] - 1s 2ms/step - loss: 0.1708 - mae: 0.2043 - mse: 0.1708 - val_loss: 0.1246 - val_mae: 0.1653 - val_mse: 0.1246
Epoch 100/100
525/525 [==============================] - 1s 3ms/step - loss: 0.1645 - mae: 0.2045 - mse: 0.1645 - val_loss: 0.1312 - val_mae: 0.1668 - val_mse: 0.1312


[I 2023-04-27 11:26:46,330] Trial 87 finished with value: 0.12637023404240608 and parameters: {'learning_rate': 0.0028637430456486448, 'dropout_rate': 0.04113156373654817, 'num_hidden_layers': 4, 'neurons_per_layer': 202, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1047/1050 [============================>.] - ETA: 0s - loss: 0.3383 - mae: 0.3650 - mse: 0.3383
Epoch: 0, loss:0.3379,  mae:0.3648,  mse:0.3379,  val_loss:0.2353,  val_mae:0.2869,  val_mse:0.2353,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.3379 - mae: 0.3648 - mse: 0.3379 - val_loss: 0.2353 - val_mae: 0.2869 - val_mse: 0.2353
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2571 - mae: 0.2905 - mse: 0.2571 - val_loss: 0.2138 - val_mae: 0.2598 - val_mse: 0.2138
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2421 - mae: 0.2745 - mse: 0.2421 - val_loss: 0.1999 - val_mae: 0.2459 - val_mse: 0.1999
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2318 - mae: 0.2637 - mse: 0.2318 - val_loss: 0.1804 - val_mae: 0.2171 - val_mse: 0.1804
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2214 - mae: 0.2547 - mse: 0.2214 - val_loss: 0.1700 - 

[I 2023-04-27 11:31:08,506] Trial 88 finished with value: 0.11620065420866013 and parameters: {'learning_rate': 0.003795608085833033, 'dropout_rate': 0.024420912475687884, 'num_hidden_layers': 6, 'neurons_per_layer': 251, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1046/1050 [============================>.] - ETA: 0s - loss: 0.3805 - mae: 0.4070 - mse: 0.3805
Epoch: 0, loss:0.3806,  mae:0.4071,  mse:0.3806,  val_loss:0.2558,  val_mae:0.3139,  val_mse:0.2558,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.3806 - mae: 0.4071 - mse: 0.3806 - val_loss: 0.2558 - val_mae: 0.3139 - val_mse: 0.2558
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2666 - mae: 0.3046 - mse: 0.2666 - val_loss: 0.2200 - val_mae: 0.2715 - val_mse: 0.2200
Epoch 3/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2497 - mae: 0.2860 - mse: 0.2497 - val_loss: 0.2032 - val_mae: 0.2533 - val_mse: 0.2032
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2360 - mae: 0.2718 - mse: 0.2360 - val_loss: 0.1930 - val_mae: 0.2419 - val_mse: 0.1930
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2290 - mae: 0.2628 - mse: 0.2290 - val_loss: 0.1816 - 

Epoch 97/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.1363 - mae: 0.1704 - mse: 0.1363 - val_loss: 0.1130 - val_mae: 0.1469 - val_mse: 0.1130
Epoch 98/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.1355 - mae: 0.1718 - mse: 0.1355 - val_loss: 0.1199 - val_mae: 0.1491 - val_mse: 0.1199
Epoch 99/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.1353 - mae: 0.1705 - mse: 0.1353 - val_loss: 0.1137 - val_mae: 0.1458 - val_mse: 0.1137
Epoch 100/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.1342 - mae: 0.1699 - mse: 0.1342 - val_loss: 0.1114 - val_mae: 0.1435 - val_mse: 0.1114


[I 2023-04-27 11:36:43,902] Trial 89 finished with value: 0.11341880187392235 and parameters: {'learning_rate': 0.002148516137087092, 'dropout_rate': 0.02427241629845673, 'num_hidden_layers': 6, 'neurons_per_layer': 251, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1038/1050 [============================>.] - ETA: 0s - loss: 0.3009 - mae: 0.2992 - mse: 0.3009
Epoch: 0, loss:0.2997,  mae:0.2987,  mse:0.2997,  val_loss:0.2001,  val_mae:0.2465,  val_mse:0.2001,  
1050/1050 [==============================] - 7s 6ms/step - loss: 0.2997 - mae: 0.2987 - mse: 0.2997 - val_loss: 0.2001 - val_mae: 0.2465 - val_mse: 0.2001
Epoch 2/100
1050/1050 [==============================] - 6s 6ms/step - loss: 0.2452 - mae: 0.2612 - mse: 0.2452 - val_loss: 0.2232 - val_mae: 0.2902 - val_mse: 0.2232
Epoch 3/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2293 - mae: 0.2519 - mse: 0.2293 - val_loss: 0.1856 - val_mae: 0.2112 - val_mse: 0.1856
Epoch 4/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2283 - mae: 0.2533 - mse: 0.2283 - val_loss: 0.1756 - val_mae: 0.2447 - val_mse: 0.1756
Epoch 5/100
1050/1050 [==============================] - 5s 4ms/step - loss: 0.2195 - mae: 0.2490 - mse: 0.2195 - val_loss: 0.1667 - 

[I 2023-04-27 11:39:17,300] Trial 90 finished with value: 0.15060924291610717 and parameters: {'learning_rate': 0.0022002724515807147, 'dropout_rate': 0.02410696314724352, 'num_hidden_layers': 6, 'neurons_per_layer': 264, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'rms'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1049/1050 [============================>.] - ETA: 0s - loss: 0.3439 - mae: 0.3746 - mse: 0.3439
Epoch: 0, loss:0.3437,  mae:0.3745,  mse:0.3437,  val_loss:0.2305,  val_mae:0.2863,  val_mse:0.2305,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.3437 - mae: 0.3745 - mse: 0.3437 - val_loss: 0.2305 - val_mae: 0.2863 - val_mse: 0.2305
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2495 - mae: 0.2875 - mse: 0.2495 - val_loss: 0.2122 - val_mae: 0.2691 - val_mse: 0.2122
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2332 - mae: 0.2697 - mse: 0.2332 - val_loss: 0.1966 - val_mae: 0.2298 - val_mse: 0.1966
Epoch 4/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2213 - mae: 0.2538 - mse: 0.2213 - val_loss: 0.1775 - val_mae: 0.2222 - val_mse: 0.1775
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2134 - mae: 0.2462 - mse: 0.2134 - val_loss: 0.1609 - 

[I 2023-04-27 11:41:25,297] Trial 91 finished with value: 0.12254154682159424 and parameters: {'learning_rate': 0.00383371017189219, 'dropout_rate': 0.02117704078014225, 'num_hidden_layers': 6, 'neurons_per_layer': 251, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1050/1050 [==============================] - ETA: 0s - loss: 0.3570 - mae: 0.3833 - mse: 0.3570
Epoch: 0, loss:0.3570,  mae:0.3833,  mse:0.3570,  val_loss:0.2446,  val_mae:0.2984,  val_mse:0.2446,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.3570 - mae: 0.3833 - mse: 0.3570 - val_loss: 0.2446 - val_mae: 0.2984 - val_mse: 0.2446
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2633 - mae: 0.2989 - mse: 0.2633 - val_loss: 0.2272 - val_mae: 0.2717 - val_mse: 0.2272
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2472 - mae: 0.2813 - mse: 0.2472 - val_loss: 0.2068 - val_mae: 0.2579 - val_mse: 0.2068
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2387 - mae: 0.2731 - mse: 0.2387 - val_loss: 0.1962 - val_mae: 0.2413 - val_mse: 0.1962
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2275 - mae: 0.2620 - mse: 0.2275 - val_loss: 0.1828 - 

[I 2023-04-27 11:44:03,186] Trial 92 finished with value: 0.11969352439045906 and parameters: {'learning_rate': 0.0027428580692919857, 'dropout_rate': 0.019494259072585913, 'num_hidden_layers': 6, 'neurons_per_layer': 237, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1033/1050 [============================>.] - ETA: 0s - loss: 0.3394 - mae: 0.3710 - mse: 0.3394
Epoch: 0, loss:0.3379,  mae:0.3699,  mse:0.3379,  val_loss:0.2443,  val_mae:0.2870,  val_mse:0.2443,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.3379 - mae: 0.3699 - mse: 0.3379 - val_loss: 0.2443 - val_mae: 0.2870 - val_mse: 0.2443
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2620 - mae: 0.2933 - mse: 0.2620 - val_loss: 0.2170 - val_mae: 0.2654 - val_mse: 0.2170
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2437 - mae: 0.2783 - mse: 0.2437 - val_loss: 0.2007 - val_mae: 0.2461 - val_mse: 0.2007
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2335 - mae: 0.2687 - mse: 0.2335 - val_loss: 0.1830 - val_mae: 0.2292 - val_mse: 0.1830
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2251 - mae: 0.2572 - mse: 0.2251 - val_loss: 0.1767 - 

[I 2023-04-27 11:47:43,690] Trial 93 finished with value: 0.11916295364499092 and parameters: {'learning_rate': 0.0032429533402044746, 'dropout_rate': 0.0267254756154759, 'num_hidden_layers': 6, 'neurons_per_layer': 261, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1045/1050 [============================>.] - ETA: 0s - loss: 0.4269 - mae: 0.4442 - mse: 0.4269
Epoch: 0, loss:0.4261,  mae:0.4436,  mse:0.4261,  val_loss:0.2668,  val_mae:0.3194,  val_mse:0.2668,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.4261 - mae: 0.4436 - mse: 0.4261 - val_loss: 0.2668 - val_mae: 0.3194 - val_mse: 0.2668
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2753 - mae: 0.3121 - mse: 0.2753 - val_loss: 0.2268 - val_mae: 0.2770 - val_mse: 0.2268
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2585 - mae: 0.2942 - mse: 0.2585 - val_loss: 0.2234 - val_mae: 0.2662 - val_mse: 0.2234
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2488 - mae: 0.2828 - mse: 0.2488 - val_loss: 0.2060 - val_mae: 0.2513 - val_mse: 0.2060
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2413 - mae: 0.2741 - mse: 0.2413 - val_loss: 0.1952 - 

[I 2023-04-27 11:50:43,022] Trial 94 finished with value: 0.12888859510421752 and parameters: {'learning_rate': 0.001934185092117727, 'dropout_rate': 0.029833897399837425, 'num_hidden_layers': 7, 'neurons_per_layer': 245, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1035/1050 [============================>.] - ETA: 0s - loss: 0.3401 - mae: 0.3678 - mse: 0.3401
Epoch: 0, loss:0.3386,  mae:0.3664,  mse:0.3386,  val_loss:0.2337,  val_mae:0.2798,  val_mse:0.2337,  
1050/1050 [==============================] - 5s 4ms/step - loss: 0.3386 - mae: 0.3664 - mse: 0.3386 - val_loss: 0.2337 - val_mae: 0.2798 - val_mse: 0.2337
Epoch 2/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2513 - mae: 0.2851 - mse: 0.2513 - val_loss: 0.2059 - val_mae: 0.2457 - val_mse: 0.2059
Epoch 3/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2365 - mae: 0.2670 - mse: 0.2365 - val_loss: 0.1887 - val_mae: 0.2377 - val_mse: 0.1887
Epoch 4/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2227 - mae: 0.2566 - mse: 0.2227 - val_loss: 0.1778 - val_mae: 0.2251 - val_mse: 0.1778
Epoch 5/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2152 - mae: 0.2462 - mse: 0.2152 - val_loss: 0.1696 - 

[I 2023-04-27 11:54:45,290] Trial 95 finished with value: 0.12023812606930732 and parameters: {'learning_rate': 0.0037283079641469504, 'dropout_rate': 0.01621699855815376, 'num_hidden_layers': 6, 'neurons_per_layer': 300, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1036/1050 [============================>.] - ETA: 0s - loss: 0.3892 - mae: 0.4155 - mse: 0.3892
Epoch: 0, loss:0.3872,  mae:0.4142,  mse:0.3872,  val_loss:0.2459,  val_mae:0.2983,  val_mse:0.2459,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.3872 - mae: 0.4142 - mse: 0.3872 - val_loss: 0.2459 - val_mae: 0.2983 - val_mse: 0.2459
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2677 - mae: 0.3024 - mse: 0.2677 - val_loss: 0.2174 - val_mae: 0.2646 - val_mse: 0.2174
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2488 - mae: 0.2830 - mse: 0.2488 - val_loss: 0.2015 - val_mae: 0.2452 - val_mse: 0.2015
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2382 - mae: 0.2729 - mse: 0.2382 - val_loss: 0.1906 - val_mae: 0.2372 - val_mse: 0.1906
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2275 - mae: 0.2623 - mse: 0.2275 - val_loss: 0.1762 - 

[I 2023-04-27 11:57:08,028] Trial 96 finished with value: 0.12538482770323753 and parameters: {'learning_rate': 0.0025215101035496778, 'dropout_rate': 0.023175651402815273, 'num_hidden_layers': 7, 'neurons_per_layer': 223, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1045/1050 [============================>.] - ETA: 0s - loss: 0.4265 - mae: 0.4443 - mse: 0.4265
Epoch: 0, loss:0.4264,  mae:0.4444,  mse:0.4264,  val_loss:0.2762,  val_mae:0.3279,  val_mse:0.2762,  
1050/1050 [==============================] - 4s 4ms/step - loss: 0.4264 - mae: 0.4444 - mse: 0.4264 - val_loss: 0.2762 - val_mae: 0.3279 - val_mse: 0.2762
Epoch 2/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2878 - mae: 0.3217 - mse: 0.2878 - val_loss: 0.2507 - val_mae: 0.2974 - val_mse: 0.2507
Epoch 3/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2763 - mae: 0.3076 - mse: 0.2763 - val_loss: 0.2375 - val_mae: 0.2837 - val_mse: 0.2375
Epoch 4/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2694 - mae: 0.3019 - mse: 0.2694 - val_loss: 0.2280 - val_mae: 0.2747 - val_mse: 0.2280
Epoch 5/100
1050/1050 [==============================] - 4s 3ms/step - loss: 0.2598 - mae: 0.2940 - mse: 0.2598 - val_loss: 0.2187 - 

[I 2023-04-27 12:02:28,055] Trial 97 finished with value: 0.12167855203151703 and parameters: {'learning_rate': 0.001304820833101806, 'dropout_rate': 0.031514938262801315, 'num_hidden_layers': 6, 'neurons_per_layer': 234, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
831/840 [============================>.] - ETA: 0s - loss: 0.4394 - mae: 0.4631 - mse: 0.4394
Epoch: 0, loss:0.4380,  mae:0.4619,  mse:0.4380,  val_loss:0.2752,  val_mae:0.3337,  val_mse:0.2752,  
840/840 [==============================] - 3s 3ms/step - loss: 0.4380 - mae: 0.4619 - mse: 0.4380 - val_loss: 0.2752 - val_mae: 0.3337 - val_mse: 0.2752
Epoch 2/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2832 - mae: 0.3203 - mse: 0.2832 - val_loss: 0.2486 - val_mae: 0.2949 - val_mse: 0.2486
Epoch 3/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2688 - mae: 0.3021 - mse: 0.2688 - val_loss: 0.2356 - val_mae: 0.2796 - val_mse: 0.2356
Epoch 4/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2564 - mae: 0.2895 - mse: 0.2564 - val_loss: 0.2241 - val_mae: 0.2713 - val_mse: 0.2241
Epoch 5/100
840/840 [==============================] - 2s 3ms/step - loss: 0.2468 - mae: 0.2805 - mse: 0.2468 - val_loss: 0.2131 - val_mae: 0.2

[I 2023-04-27 12:05:28,423] Trial 98 finished with value: 0.11878685355186462 and parameters: {'learning_rate': 0.0017131707829217756, 'dropout_rate': 0.01851876225337959, 'num_hidden_layers': 6, 'neurons_per_layer': 209, 'batch_size': 10, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


Epoch 1/100
1046/1050 [============================>.] - ETA: 0s - loss: 0.3159 - mae: 0.3458 - mse: 0.3159
Epoch: 0, loss:0.3154,  mae:0.3455,  mse:0.3154,  val_loss:0.2294,  val_mae:0.2725,  val_mse:0.2294,  
1050/1050 [==============================] - 4s 3ms/step - loss: 0.3154 - mae: 0.3455 - mse: 0.3154 - val_loss: 0.2294 - val_mae: 0.2725 - val_mse: 0.2294
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2554 - mae: 0.2883 - mse: 0.2554 - val_loss: 0.2153 - val_mae: 0.2598 - val_mse: 0.2153
Epoch 3/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2395 - mae: 0.2705 - mse: 0.2395 - val_loss: 0.1892 - val_mae: 0.2443 - val_mse: 0.1892
Epoch 4/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2279 - mae: 0.2613 - mse: 0.2279 - val_loss: 0.1750 - val_mae: 0.2251 - val_mse: 0.1750
Epoch 5/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2148 - mae: 0.2504 - mse: 0.2148 - val_loss: 0.1684 - 

[I 2023-04-27 12:08:14,727] Trial 99 finished with value: 0.12465600222349167 and parameters: {'learning_rate': 0.005019962381559987, 'dropout_rate': 0.026068624202812255, 'num_hidden_layers': 5, 'neurons_per_layer': 272, 'batch_size': 8, 'activation': 'relu', 'optimizer': 'sgd'}. Best is trial 59 with value: 0.11328117623925209.


In [10]:
print(best_params, best_score)

{'learning_rate': 0.003931416839453604, 'dropout_rate': 0.024815972888615808, 'num_hidden_layers': 6, 'neurons_per_layer': 217, 'batch_size': 16, 'activation': 'relu', 'optimizer': 'sgd'} 0.11328117623925209


In [11]:

# Build the Keras model with the best hyperparameters
model = get_keras_model(best_params['num_hidden_layers'], 
                        best_params['neurons_per_layer'], 
                        best_params['dropout_rate'], 
                        best_params['activation'])

opt = best_params['optimizer']
opt = opt.lower()

learning_rate = best_params['learning_rate']

if opt == 'adam':
    optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
elif opt == 'rms':
    optimizer = tf.keras.optimizers.RMSprop(learning_rate=learning_rate)
else:
    optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate)

model.compile(optimizer=optimizer,
              loss=tf.keras.losses.MeanSquaredError(),
              metrics=['mae', 'mse'])

# Train the model on the entire training set
nn= model.fit(X_train, y_train, epochs=100, batch_size=best_params['batch_size'])


Epoch 1/100
657/657 [==============================] - 3s 3ms/step - loss: 0.3703 - mae: 0.3948 - mse: 0.3703
Epoch 2/100
657/657 [==============================] - 2s 3ms/step - loss: 0.2563 - mae: 0.2956 - mse: 0.2563
Epoch 3/100
657/657 [==============================] - 2s 3ms/step - loss: 0.2404 - mae: 0.2780 - mse: 0.2404
Epoch 4/100
657/657 [==============================] - 2s 3ms/step - loss: 0.2274 - mae: 0.2647 - mse: 0.2274
Epoch 5/100
657/657 [==============================] - 2s 3ms/step - loss: 0.2184 - mae: 0.2564 - mse: 0.2184
Epoch 6/100
657/657 [==============================] - 2s 3ms/step - loss: 0.2143 - mae: 0.2505 - mse: 0.2143
Epoch 7/100
657/657 [==============================] - 2s 3ms/step - loss: 0.2076 - mae: 0.2441 - mse: 0.2076
Epoch 8/100
657/657 [==============================] - 2s 3ms/step - loss: 0.1996 - mae: 0.2364 - mse: 0.1996
Epoch 9/100
657/657 [==============================] - 2s 3ms/step - loss: 0.2009 - mae: 0.2352 - mse: 0.2009
Epoch 10/1

In [12]:
from sklearn.metrics import mean_squared_error
y_pred = model.predict(X_test)

print('Mean Square Error:', round(mean_squared_error(y_test,y_pred), 3))

Mean Square Error: 0.132


# Conclusions

The mse of 0.132 is the best value of mse obtained so far (KNN 0.186, KNN colour 0.149, NN 0.145). But it is still to high with respect of the SDSS photometric redshifht of 0.054. This could be due to the fact that there are not enough sources with z > 1.